GetStream/stream-video-swift

.github/workflows/publish-release.yml, .github/workflows/smoke-checks.yml, Gemfile.lock, README.txt, Sources/StreamVideo/Info.plist, Sources/StreamVideoSwiftUI/CallingViews/CallBackgrounds.swift, Sources/StreamVideoSwiftUI/Info.plist, Sources/StreamVideoSwiftUI/Utils/LazyImageExtensions.swift, Sources/StreamVideoSwiftUI/Utils/UserAvatar.swift, Sources/StreamVideoUIKit/Info.plist, StreamVideo.podspec, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUI.podspec, StreamVideoUIKit.podspec, fastlane/Fastfile, fastlane/Pluginfile
Test the release pipeline
- `publish-release.yml` is disabled in [GitHub Actions UI](https://github.com/GetStream/stream-video-swift/actions/workflows/publish-release.yml) until we implement a `develop` branch, i.e. currently **releasing is only possible locally**.
- This [release action](https://github.com/GetStream/fastlane-plugin-stream_actions/blob/main/lib/fastlane/plugin/stream_actions/actions/release_ios_sdk.rb) is shared across all iOS SDKs
- `LazyImage` is extended to support both SPM and CocoaPods distribution
=> Update release pipeline

docusaurus/docs/iOS/03-guides/05-call-types.mdx
Use the shared page we have for call types.
The content of the call types page is similar across SDKs so we created a shared one (with content that is not yet complete). This PR uses that shared page. Once the content of the shared page is finalized it will automatically be distributed across SDKs (including iOS).
If interested, the page can be found [here](https://github.com/GetStream/stream-chat-docusaurus-cli/blob/staging/shared/video/_call-types.md).
I don't like fun.
=> Use the shared call types page

Gemfile.lock, fastlane/Pluginfile
Testflight upload fails if release to App Store was done manually. This PR should solve [this](https://github.com/GetStream/stream-video-swift/actions/runs/5587921433). 
All magic here: https://github.com/GetStream/fastlane-plugin-stream_actions/commit/8e7ad3d5317320fa655fa0ade112270ea646afcb
=> Update app version as part of Testflight upload

docusaurus/docs/iOS/02-tutorials/02-audio-room-uikit.mdx, docusaurus/sidebars-ios.js
https://github.com/GetStream/stream-video-swift/assets/472467/6117d604-5cfd-46a9-8240-ec6aaa989271
=> [Docs]Create UIKit tutorial for AudioRooms

.github/workflows/cron-checks.yml, .github/workflows/smoke-checks.yml, .slather.yml, DemoApp/CallView.swift, DemoApp/LocalStorage.swift, DemoApp/StreamVideoSwiftUIApp.swift, DemoApp/TokenService.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideo.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme, StreamVideo.xcodeproj/xcshareddata/xcschemes/DemoAppUIKit.xcscheme, StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideo.xcscheme, StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideoSwiftUI.xcscheme, StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideoUIKit.xcscheme, StreamVideoTests/IntegrationTests/IntegrationTest.swift, SwiftUIDemoAppUITests/Pages/CallDetailsPage.swift, SwiftUIDemoAppUITests/Robots/UserRobot+Asserts.swift, SwiftUIDemoAppUITests/Robots/UserRobot.swift, SwiftUIDemoAppUITests/SwiftUIDemoApp.xctestplan, SwiftUIDemoAppUITests/Tests/Authentication_Tests.swift, SwiftUIDemoAppUITests/Tests/CallLifecycleTests.swift, SwiftUIDemoAppUITests/Tests/CallViewsTests.swift, SwiftUIDemoAppUITests/Tests/ParticipantActionsTests.swift, SwiftUIDemoAppUITests/Tests/StreamTestCase.swift, TestTools/TestData/LaunchArgument.swift, TestTools/TestData/TokenGenerator.swift, fastlane/Fastfile, fastlane/Scanfile
- Add E2E JWT tests
- Create new configuration `Test` to make it easier to use environment variables and macros across all test targets
- Moved `Credentials.xcconfig` to a shared place
- Move `StreamVideoTests/IntegrationTests/Credentials.xcconfig` to `TestTools/Credentials.xcconfig`
=> Add E2E JWT tests

CHANGELOG.md, PrivacyInfo.xcprivacy, StreamVideo.xcodeproj/project.pbxproj
Resolves https://github.com/GetStream/ios-issues-tracking/issues/516
- Align with new Apple privacy requirements
- [Privacy manifests](https://developer.apple.com/wwdc23/10060)
- Inject `PrivacyInfo.xcprivacy` to `StreamVideo`, `StreamVideoSwiftUI` and `StreamVideoUIKit` binaries
=> Add PrivacyInfo

DemoApp/Info.plist
Without the `Requires fullscreen` configuration wet get the following error when releasing to the AppStore
```
Asset validation failed Invalid bundle. Because your app supports Multitasking on iPad, you need to include the LaunchScreen launch storyboard file in your io.getstream.iOS.VideoDemoApp bundle. Use UILaunchScreen instead if the app’s MinimumOSVersion is 14 or higher and you prefer to configure the launch screen without storyboards.
```
=> [Fix]Missing configuration

DemoApp/Sources/Components/MemoryLogDestination/LogQueue.swift, DemoApp/Sources/Components/MemoryLogDestination/MemoryLogDestination.swift, DemoApp/Sources/Components/MemoryLogDestination/MemoryLogViewer.swift, DemoApp/Sources/Extensions/DemoApp+Sentry.swift, DemoApp/Sources/Views/Login/DebugMenu.swift, StreamVideo.xcodeproj/project.pbxproj
On debug builds, provide an easy way to look into realtime logs for issues and anomalies.
Implementing a Debug only View that renders logs and integrate it with SDK's logger.
|  Log List  |  Log Entry  |
| ![Simulator Screenshot - iPhone 14 Pro - 2023-09-04 at 13 26 48](https://github.com/GetStream/stream-video-swift/assets/472467/6bb0ea74-e650-4306-a279-7d0c36a0c059) | ![Simulator Screenshot - iPhone 14 Pro - 2023-09-04 at 13 26 57](https://github.com/GetStream/stream-video-swift/assets/472467/8f74cc16-b4cb-4195-809b-9fd0f3a227e5) |
=> [Logs]Implement log viewer

DemoApp/Resources/Entitlements/DemoApp-Debug.entitlements, DemoApp/Resources/Entitlements/DemoApp.entitlements, DemoApp/Sources/AppDelegate.swift, DemoApp/Sources/Components/AppEnvironment.swift, DemoApp/Sources/Components/MemoryLogDestination/OSLogDestination.swift, DemoApp/Sources/Components/Router.swift, DemoApp/Sources/Extensions/DemoApp+Sentry.swift, DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift, StreamVideo.xcodeproj/project.pbxproj, SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift, TestTools/UITests/Safari.swift, TestTools/UITests/XCUIApplication+KeyboardIntroduction.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/571
Ensure deeplinks are working consistently
A few issues discovered:
- Association file was broken
- Missing the implementation method that iOS seems to call for universal links but not for custom schemes
Implemented UITests that validate deeplink handling for 
- Universal links (via the smart banner open button)
- Custom URL schemes
=> [Fix]Deeplink handling

Sources/StreamVideo/Utils/ThermalStateObserver.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Utils/ThermalStateObserverTests.swift
=> [Fix]Thermal State not updating

DemoApp/Sources/Views/ThermalStateViewModifier/ThermalStateViewModifier.swift, Sources/StreamVideo/Utils/ThermalStateObserver.swift, Sources/StreamVideo/WebRTC/WebRTCClient.swift, Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/CallView/VideoRenderer_Tests.swift, StreamVideoTests/Utils/ThermalStateObserverTests.swift
Adapt framerate for VideoRenderer (in oder to reduce CPU usage) when device's thermal state changes.
By observing the thermal state we respond to changes on the thermal state. The goal is to reduce CPU requirements to render video tracks in order to allow the device to cool down or maintain its usage to a steady level.
=> Adaptive frame rate depending on thermalState

CHANGELOG.md, Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
=> Fix current user overlay view size when camera is off

DemoApp/Sources/Views/Login/GoogleHelper.swift, Sources/StreamVideo/CallState.swift, Sources/StreamVideo/Utils/Sorting.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/CallViewModel_Tests.swift, StreamVideoTests/CallState/CallState_Tests.swift, StreamVideoTests/Controllers/CallController_Tests.swift, StreamVideoTests/Mock/CallParticipant_Mock.swift, StreamVideoTests/Mock/MockResponseBuilder.swift, StreamVideoTests/Utils/Sorting_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/582
Avoid moving video tracks when user properties change, especially when that user is currently visible.
Based on React implementation [here](https://github.com/GetStream/stream-video-js/blob/main/packages/client/src/sorting/presets.ts)
=> Align participants sorting with Web

DemoApp/Sources/Components/DemoAppViewFactory.swift, DemoApp/Sources/Views/CallView/DemoCallView.swift, DemoApp/Sources/Views/CustomCallView.swift, Sources/StreamVideoSwiftUI/CallView/LocalParticipantViewModifier.swift, Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift, Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift, Sources/StreamVideoSwiftUI/CallingViews/iOS13/PreJoiningView_iOS13.swift, StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
MicrophoneChecker's operations to startListening(create new recording file), update volume meters and stop recording (delete recording file) can be quite expensive when occuring multiple times per second. 
We are using our injection system to create an instance for the MicrophoneChecker that can be overriden.
=> Use single instance for the microphoneChecker

.github/workflows/cron-checks.yml, .github/workflows/smoke-checks.yml, SwiftUIDemoAppUITests/Robots/UserRobot+Asserts.swift, SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift, TestTools/Robots/Sinatra.swift, TestTools/UITests/Safari.swift, fastlane/sinatra.rb
Downgrading the macos version from 13 to 12 seems to improve a lot the stability and speed. For now, let's run it there and take another look at tests' performance after Xcode 15.1 is available on CI.
=> Fix flaky E2E tests

CHANGELOG.md, Sources/StreamVideo/Generated/SystemEnvironment+Version.swift, Sources/StreamVideo/Info.plist, Sources/StreamVideoSwiftUI/Info.plist, Sources/StreamVideoUIKit/Info.plist, StreamVideo-XCFramework.podspec, StreamVideo.podspec, StreamVideoArtifacts.json, StreamVideoSwiftUI-XCFramework.podspec, StreamVideoSwiftUI.podspec, StreamVideoUIKit-XCFramework.podspec, StreamVideoUIKit.podspec
- Nuke dependency is no longer exposed. If you were using this dependency we were exposing, you would need to import it manually. This is due to our newest addition supporting Module Stable XCFramework, see more below in the "Added" section. If you encounter any SPM-related problems, be sure to reset the package caches.
- Add support for pre-built XCFrameworks
- Fast reconnection
- New redesigned UI components. [#236](https://github.com/GetStream/stream-video-swift/pull/236)
- You can now focus on a desired point in the local video stream. [#221](https://github.com/GetStream/stream-video-swift/pull/221)
- The following API changes occurred as part of the redesign. [#221](https://github.com/GetStream/stream-video-swift/pull/221)
- `CornerDragableView` has been renamed to …
=> 0.4.2 Release

Sources/StreamVideo/WebRTC/SfuMiddleware.swift, Sources/StreamVideo/WebRTC/WebRTCClient.swift, Sources/StreamVideoSwiftUI/CallView/LayoutComponents/HorizontalParticipantsListView.swift, Sources/StreamVideoSwiftUI/CallView/LayoutComponents/SpotlightSpeakerView.swift, Sources/StreamVideoSwiftUI/CallView/ParticipantsGridView.swift, Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift, Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift, Sources/StreamVideoSwiftUI/CallView/VisibilityThresholdModifier.swift
Ensure that video tracks are always visible.
There are a two underline issues resulting in this bug:
- When a user stops publishing video (that is translated as track muted for BE) we remove the track from our array and then we stop receiving events about it whenever the user decides to re-enable their camera.
- The visibility observation was being added on the view ONLY when the participant had video. When the user reenables their video the view doesn't fire the geometry calculation causing the view to not trigger the track visibility change.
- For local track we rely on 2 input signals to disable the track a) we disable locally the track we have a reference to, b) we send a mute request to the SFU which replies with an event that updates the participant to `hasVideo:false`. Due to this …
=> [Fix]VideoRenderers being added in multiple superviews

Sources/StreamVideo/HTTPClient/InternetConnection.swift
Same fix as in the chat client: https://github.com/GetStream/stream-chat-swift/pull/2923/files.
=> Improved InternetConnection.Monitor stability

Sources/StreamVideoSwiftUI/CallView/CallParticipantImageView.swift, Sources/StreamVideoSwiftUI/CallingViews/CallBackgrounds.swift, Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift, Sources/StreamVideoSwiftUI/Utils/LazyImageExtensions.swift, Sources/StreamVideoSwiftUI/Utils/UserAvatar.swift
Provide a failback View to render when Nuke fails to fetch or decode the image.
Due to a recent change on BE now all users contain default imageURL. Unfortunately this URL points to an SVG image which Nuke fails to render. This PR adds a way to provide a failback View to render whenever Nuke fails.
=> [Fix]When Nuke fails render failback

docusaurus/docs/iOS/03-guides/05-call-types.mdx
Fix broken links in the call types shared page.
- Update docusaurus cli to latest `production`
- Run `npx stream-chat-docusaurus -i -s` 
- Open the three tutorial links
=> Fixed call types tutorial links

DemoApp/Sources/Components/Router.swift, DemoApp/Sources/DemoApp.swift, Sources/StreamVideoSwiftUI/StreamVideoUI.swift, Sources/StreamVideoSwiftUI/Utils.swift
- UserState: By having the AppState as a StateObject on the DemoApp we were causing rerenders on the View everytime the AppState was changing, causing cases where we had more than one CallViewModel instances available.
- Utils: The way we were instatiating and injecting the values was resulting in more than one instances to be available during runtime. That's causing issues like the missing tracks as there are different videoRendererFactories that being involved during the call.
=> Fix memory leaks on Utils and UserState

Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
=> [Fix]Only reuse VideoRenderers when they are actually presented

DemoApp/Sources/Components/AppEnvironment.swift, DemoApp/Sources/Views/CallView/DemoCallContainerView.swift, DemoApp/Sources/Views/Login/DebugMenu.swift
Provide a toggle that can be used as an example for integrators that would like to disable Picture in Picture.
=> [Integration]Add toggle for picture in picture

StreamVideoTests/IntegrationTests/CallCRUDTests.swift
Following the cursor, we were also getting data that didn't make much sense, with the existing callId at the top:
```
25 elements
- 0 : "A6F90889-653C-4B23-9438-96CC942FF141"
- 1 : "C86AEEDB-9ADD-4108-B02D-6310C85696E4"
- 2 : "2B3B4A9A-22AA-4D7F-A97A-29F056937F89"
- 3 : "B2F70597-7A46-41E5-A225-E8C6CD775BD8"
- 4 : "602a6dbf-689b-4b82-bc01-0afc1d6015ce"
- 5 : "call73172a71-433e-42c9-a0bb-22360637ec21"
- 6 : "call4a0d66af-7c7d-452b-81a5-c6ee74fb6335"
- 7 : "a8c0f21f-fbd7-49ef-9efc-4597d31c0e6f"
- 8 : "call41ef65cd-1cf4-4ec0-ae90-0853e8cae7f9"
- 9 : "call89423f2b-3577-4203-a34c-9411ff33418d"
- 10 : "e2e-test-a75a5ccaaae29"
- 11 : "e2e-test-9f8b46fda5625"
- 12 : "e2e-test-3b6e861506bb4"
- 13 : "e2e-test-ddbc158b2f1f1"
- 14 : "e2e-test-25595ef6f4d6d"
- 15 : "e2e-test-5cabd18441ebd"
- 16 : …
```
=> Remove next assertion

Gemfile, Gemfile.lock, TestTools/Robots/Sinatra.swift
- Fix issues related to Sinatra server
- Gemfile refactoring
=> Gemfile refactoring

Sources/StreamVideo/OpenApi/generated/APIs/DefaultAPI.swift
We don't encode dates properly atm. Therefore, if you want to e.g. create a meeting in the future, it doesn't work.
Will also fix it in the generator, but that's a separate place.
=> Fix encoding of dates as parameters in the requests

Sources/StreamVideoSwiftUI/Utils/Extensions/CVPixelBuffer+Convenience.swift, Sources/StreamVideoSwiftUI/Utils/Extensions/RTCCVPixelBuffer+Convenience.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamBufferTransformer.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureVideoRenderer.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/Utils/PictureInPicture/StreamBufferTransformerTests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/706
In the latest improvement work that we did to Picture in Picture we introduced cropAndScale to frames that use an RTCI420Buffer underline buffer. That improved memory consumption for most devices. However, some newer devices (e.g. iPad Pro models) are receiving frames that are using RTCCVPixelBuffer underneath. Those frames weren't optimised which resulted in CPU and memory spiking when rendering tracks with sizes much bigger than the PiP window, leading to crashes.
The PR makes the existing StreamBufferTransformer's API generic so we can reuse the logic that we have in place to cropAndScale RTCCVPixelBuffer.
- Testing requires iPad [devices](https://support.apple.com/en-sg/guide/ipad/aside/ipad7a0645dd/17.0/ipados/17.0) …
=> [Fix]Crop & Scale RTCCVPixelBuffer frames

CHANGELOG.md, Sources/StreamVideo/Generated/SystemEnvironment+Version.swift, Sources/StreamVideo/Info.plist, Sources/StreamVideoSwiftUI/Info.plist, Sources/StreamVideoUIKit/Info.plist, StreamVideo-XCFramework.podspec, StreamVideo.podspec, StreamVideoArtifacts.json, StreamVideoSwiftUI-XCFramework.podspec, StreamVideoSwiftUI.podspec, StreamVideoUIKit-XCFramework.podspec, StreamVideoUIKit.podspec
- The following API changes occurred as part of the redesign. [#269](https://github.com/GetStream/stream-video-swift/pull/269) & [#270](https://github.com/GetStream/stream-video-swift/pull/270)
- `OutgoingCallView` now accepts an additional `callTopView` parameter to align with the updated design.
- `CallParticipantsInfoView` and the `ViewFactory.makeParticipantsListView` method aren't accept the `availableFrame` anymore.
- `ParticipantsGridLayout` `orientation` parameter isn't required anymore.
- The `onRotate` ViewModifier has been removed. You can use the `InjectedValues[\.orientationAdapter]` which is an ObservableObject that can provide information regarding device orientation.
=> 0.5.0 Release

CHANGELOG.md, DemoApp/Sources/Components/Snapshot/LocalParticipantSnapshotViewModel.swift, DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift, DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/16-snapshot.swift, Sources/StreamVideo/Call.swift, Sources/StreamVideo/Controllers/CallController.swift, Sources/StreamVideo/WebRTC/VideoCapturer.swift, Sources/StreamVideo/WebRTC/WebRTCClient.swift, docusaurus/docs/iOS/05-ui-cookbook/16-snapshot.mdx, docusaurus/docs/iOS/05-ui-cookbook/17-camera-zoom.mdx
Allow removing custom videoOutputs in order to avoid performance hiccups when not necessary.
=> [Improvement]Allow removing videoOutputs from AVCaptureSession

StreamVideo-XCFramework.podspec, StreamVideo.podspec
It seems like `wget` is not pre-installed on macOS, but `curl` is.
Tested `StreamVideo.podspec` with a local path:
=> Replace wget with curl in cocoapods prepare command

DemoApp/Sources/Components/Services/CallService.swift, DemoApp/Sources/Components/Services/VoIPPushService.swift, DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/02-push-notifications.swift, docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
In the DemoApp (debug builds only) there is a rare issue that can happen, if someone rings a user who just signed out from the app. The signed out user will still receive the notification and join the call because we are not unregistering from the CallService notifications.
- Get 2 users signed in on different devices.
- Logout one of them and at the same time call the logged out user from the other device.
=> [DemoApp & Docs]CallService unregister

DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift, DemoApp/Sources/Views/CallView/DemoCallView.swift, DemoApp/Sources/Views/CustomCallView.swift, DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/11-speaking-while-muted.swift, Sources/StreamVideo/Models/CallSettings.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/Utils/AudioRecorder/AVAudioRecorderBuilder.swift, Sources/StreamVideo/Utils/AudioRecorder/AudioSessionProtocol.swift, Sources/StreamVideo/Utils/AudioRecorder/StreamActiveCallProvider.swift, Sources/StreamVideo/Utils/AudioRecorder/StreamAudioRecorder.swift, Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift, Sources/StreamVideoSwiftUI/CallContainer.swift, Sources/StreamVideoSwiftUI/CallView/CallTopView.swift, Sources/StreamVideoSwiftUI/CallView/LocalParticipantViewModifier.swift, Sources/StreamVideoSwiftUI/CallView/VideoRendererFactory.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift, Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift, Sources/StreamVideoSwiftUI/CallingViews/PreJoiningViewModel.swift, Sources/StreamVideoSwiftUI/CallingViews/iOS13/PreJoiningView_iOS13.swift, Sources/StreamVideoSwiftUI/Utils/Camera.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift, StreamVideoTests/Utils/StreamAudioRecorderTests.swift, StreamVideoTests/Utils/StreamCallAudioRecorderTests.swift, SwiftUIDemoAppUITests/Robots/UserRobot+Asserts.swift, docusaurus/docs/iOS/05-ui-cookbook/11-speaking-while-muted.mdx
AVAudioRecorder is an expensive resource. This PR aims to centralise its usage and maintain a single instance during runtime, that will be initialized once and early to avoid delays during the call.
- Abstract the AVAudioRecorder behind a specialized, thread safe object.
- Inject it into the UI components and update paths accordingly.
- Minor UI updates to make the interface smoother.
- Extensive unit testing for the recording layer.
|  Lobby  |  Join Call  | Leave Call|
| ------- | ----------- | --------- |
|  true   |  true       | false     |
|  false  |  false      | false     |
|  false  |  true       | true      |
|  true   |  false      | false     |
=> [Fix]Single instance AVAudioRecorder

Sources/StreamVideo/WebRTC/Screensharing/BroadcastScreenCapturer.swift, Sources/StreamVideo/WebRTC/Screensharing/ScreenshareCapturer.swift
The RTCCameraVideoCapturer does much more than sending data to the server. As this functionality isn't required when screensharing or broadcasting, we switch back to plain RTCVideoCapturer which is the best intermediate between us getting frames and the WebRTC stack.
- Join a call
- Screenshare you screen
=> Remove unnecessary usage of RTCCameraVideoCapturer

Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamBufferTransformer.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureController.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureVideoRenderer.swift, StreamVideoSwiftUITests/Utils/PictureInPicture/StreamBufferTransformerTests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/731 & https://github.com/GetStream/ios-issues-tracking/issues/732
Stabilise memory consumption while on Picture-in-Picture.
Due to wrong implementation we were doing unnecessary buffer conversions prior to resizing to the required size (which costs a lot as we process more data than we need).
- Join a call with other participants
- Move to background
- Let the participants take rounds talking (to validate that the active track is changing)
- Stay in Picture-in-Picture fora few minutes
=> [Fix]Picture-in-Picture memory consumption

Sources/StreamVideoSwiftUI/CallViewModel.swift
When a call fails to join from the LobbyView the audioRecorder isn't being stopped from recording. This PR fixes that.
- Run the app on debugger
- Choose to login with a guest account (not one of the predefined ones)
- Enter any callId and click join
- In the lobbyView don't turn off the mic
- Press join
- After the error there should be no audioRecording.
=> [Fix]Stop recording when error occurs on join

CHANGELOG.md, DemoApp/Sources/Components/Services/CallKitService.swift, DemoApp/Sources/Components/Services/CallService.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/747
When a user is logged out but is being involved in a ringing call the VoIP push notifications will be sent to their device once they get back online (and register their device token). This PR addresses an issue where VoIP push notifications for ended/rejected calls were displayed to the user.
The easiest way is by changing the code for the DemoApp. Spefically:
- Comment out `Router.swift:50` to disable auto login
- Delete the DemoApp from the device
- Build and run
- From another device use the Detailed LoggedIn view and call one of the predefined users a few times. Make sure to select the ring events and always generate a new callId
- On the device that you built and run choose the user you called from the list
- You …
=> [Fix]Handle VoIP notifications for ended calls

Sources/StreamVideo/StreamVideo.swift
Make sure that long user ids won't be presented on UI.
| ![before](https://github.com/GetStream/stream-video-swift/assets/472467/161c8fb3-cf22-4320-ab1c-92f72de440f0) | ![after](https://github.com/GetStream/stream-video-swift/assets/472467/81dcc40f-49e8-4dba-abc2-74fdd390ffbd) |
=> [Fix]Long usernames on various places

DemoApp/Sources/AppDelegate.swift, DemoApp/Sources/Components/Services/CallKitService.swift, DemoApp/Sources/Components/Services/CallService.swift, StreamVideo.xcodeproj/project.pbxproj, docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
CallKit can become very strict with apps that do not report the incoming calls immediately. For that reason we first report the call and then we perform any callState specific action.
- Login on Simulator with userA
- Login on Device with userB
- Run the app for both users (userA should use the `Detailed` view to be able to make calls)
- Make a call (from userA on the Simulator) and answer it from the IncomingCallView on userB device (while ensuring you received the VoIP notification)
- End the call
- Repeat the make call step and this time answer the call from the VoIP notification
- End the call
- Move the userB app to the background
- From userA make another call and answer it from the VoIP notification on userB
- End the call
- Kill the app on userB device
- From userA make another …
=> [Fix]CallKit crash and Call management

Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift
When we close the lobby (by tapping the x(close button) on the top right corner) I noticed that we don't stop recording. This PR addresses this issue, by explicitly calling `stopRecording` on the microphoneCheker.
- Run the app on a device or simulator
- Type in any callId and tap Join Call
- You will notice some logs like this one `🎙️Recording meters updated`
- Tap the close button, on the top right corner
- You should not see any further messages about recording
=> [Fix]Stop recording when closing the Lobby

Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift
Since we are using a single AVAudioRecorder instance, measuring the time that takes to create it isn't useful any more.
=> [CleanUp]Remove AVAudioRecorder creation timing

DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift, DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj, DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/18-transcriptions.swift, Sources/StreamVideo/Call.swift, Sources/StreamVideo/CallState.swift, Sources/StreamVideo/Utils/Models+Sendable.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Call/Call_Tests.swift, docusaurus/docs/iOS/05-ui-cookbook/18-transcriptions.mdx
Resolves https://github.com/GetStream/ios-issues-tracking/issues/797
Provide an easy way for users to toggle transcription.
This PR exposes the required API from `Call` (while updating the DemoApp and Tests) and adds a new Cookbook that explains how to toggle Transcription on/off.
=> [Feature]Toggle Transcriptions

CHANGELOG.md, Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift, StreamVideoTests/CallKit/CallKitPushNotificationAdapterTests.swift, docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
Resolves https://getstream.zendesk.com/agent/tickets/49108
VoIP push notification contain a calculated `call_display_name` property that can be used to present a more informative name for the call (useful in group call cases).
=> Handle `call_display_name` on VoIP notifications

DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift, docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
The CallKit integration docs weren't covering the VoIP push notification registration part.
=> [Fix]VoIP Push Notification registration docs

PrivacyInfo.xcprivacy
Resolve https://github.com/GetStream/stream-video-swift/issues/365
Resolve Apple warnings:
- NSPrivacyAccessedAPICategorySystemBootTime
- NSPrivacyAccessedAPICategoryFileTimestamp
=> Update privacy policy

StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift, StreamVideoTests/WebRTC/WebRTCClient_Tests.swift
Tests were failing due to the lifecycle of the StreamAudioProcessingModule (which is being attached on WebRTC and that is holding a reference on it). Replacing the StreamAudioProcessingModule to MockAudioProcessingModule, tests fixes the issue.
=> [Fix]Failing tests due to AudioProcessingModule lifecycle

Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/Utils/Atomic.swift, Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift, Sources/StreamVideo/Utils/Sorting.swift, Sources/StreamVideo/Utils/StreamRuntimeCheck.swift, Sources/StreamVideo/Utils/ThermalStateObserver.swift, Sources/StreamVideo/WebRTC/Screensharing/BroadcastObserver.swift, Sources/StreamVideo/WebRTC/Screensharing/BroadcastSampleHandler.swift, Sources/StreamVideo/WebRTC/SimulatorScreenCapturer.swift, StreamVideoSwiftUITests/CallViewModel_Tests.swift, StreamVideoTests/IntegrationTests/IntegrationTest.swift
=> [LLC]Public interface cleanup

DemoApp/Sources/Components/AppState.swift, Sources/StreamVideo/Call.swift, Sources/StreamVideo/VideoConfig.swift, Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift, Sources/StreamVideo/WebRTC/AudioFilter/StreamAudioFilterCapturePostProcessingModule.swift, Sources/StreamVideo/WebRTC/AudioFilter/StreamAudioProcessingModule.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Mock/VideoConfig+Dummy.swift
Integrate with `StreamVideoNoiseCancellation` and cleanUp the API for noiseCancellation.
The biggest change in the PR is the removal of Concurrency in the NoiseCancellationFilter and the ProcessingModule. WebRTC provides the [thread-safety](https://chromium.googlesource.com/external/webrtc/stable/webrtc/+/b8a655ac3c71977abf0e8d657dbe9d0aec633ff9/modules/audio_processing/include/audio_processing.h#79) that we need. Additionally, swift concurrency doesn't work great with multiple thread processing buffers that are coming in, in a serial way.
The other big change is the change of type for VideoConfig, from `struct` to `class`. That seems to be necessary otherwise i noticed crashes on startup where the videoConfig was copied in different places and trying to access the processing module.
- …
=> [NoiseCancellation]Integrate and cleanUp

Sources/StreamVideoSwiftUI/Utils/AsyncImage/StreamAsyncImage.swift
It seems that AsyncImage doesn't work as expected on iOS 15 and below. This PR enables StreamAsyncImage underhood for iOS versions prior to 16.
| ![before](https://github.com/GetStream/stream-video-swift/assets/472467/da98faed-22be-4e68-88bf-08af05095ef0) | ![after](https://github.com/GetStream/stream-video-swift/assets/472467/da7ae826-17c0-4827-97ad-7265f15ce263) |
=> [Fix]AsyncImage on iOS 15 and below

Sources/StreamVideo/Call.swift, Sources/StreamVideo/CallKit/CallKitService.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/CallKit/CallKitServiceTests.swift, StreamVideoTests/Mock/CallController_Mock.swift, StreamVideoTests/Mock/MockCXCallController.swift, StreamVideoTests/Mock/MockCall.swift, StreamVideoTests/Mock/MockStreamVideo.swift, StreamVideoTests/TestUtils/Mockable.swift, StreamVideoTests/Utilities/Dummy/Credentials+Dummy.swift, StreamVideoTests/Utilities/Dummy/JoinCallResponse+Dummy.swift, StreamVideoTests/Utilities/Dummy/MemberResponse+Dummy.swift, StreamVideoTests/Utilities/Dummy/SFUResponse+Dummy.swift
This PR attempts to provide an infrastructure that will allow us to test our Core flow using unit tests. This is crucial to increase our confidence on product stability but also to remove our dependency on UI tests that as they increase in number are slowing our pipelines.
The new `Mockable` implementation provides a consistent way that allows the creation of mocks for any reference value type while allowing mocking it's method calls. It relies on dynamicmemberlookup and function overrides.
The updated `CallKitServiceTests` provide a demonstration of the new Mockable implementation. For the purpose of the tests we have provided mocks for StreamVideo and Call, both are core objects in our stack.
=> [Improvement]Testing

CHANGELOG.md, Sources/StreamVideo/WebRTC/WebRTCClient.swift
Video tracks started appearing after the first participant update. The reason was that the flow of events is a bit different for anonymous users - they don't receive all events. 
The fix is that whenever we connect, we instruct one update participation subscriptions call.
=> Video tracks for anonymous users not displaying

DemoApp/Sources/Components/Snapshot/LocalParticipantSnapshotViewModel.swift, DemoApp/Sources/Extensions/DemoApp+Sentry.swift, Sources/StreamVideo/Call.swift, Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideo/Controllers/CallController.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift, Sources/StreamVideo/Utils/UnfairQueue/UnfairQueue.swift, Sources/StreamVideo/WebRTC/WebRTCClient.swift, Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessParticipantsListButton.swift, Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift, Sources/StreamVideoSwiftUI/CallView/ViewModifiers/CallEndedViewModifier.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureAdapter.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideo.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
Allow `Call` objects to release when not in use to deallocate unnecessarily used resources.
=> [Fix]Memory issues causing Call objects to leak

CHANGELOG.md, Sources/StreamVideo/Call.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/Utils/CallCache/CallCache.swift, Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessHangUpIconView.swift, Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Mock/MockResponseBuilder.swift, StreamVideoTests/StreamVideo_Tests.swift, StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift, StreamVideoTests/Utils/CallCache_Tests.swift
Use single instances for `Call` objects with the same `cId`. That helps ensuring that irregardless of the `Call` object creation point, actions performed to it will be synced across every observer.
`StreamVideo` and `Call` internally use a thread-safe cache that ensures that only a single instance of `Call` object will exist for the same cId.
- Regular join call flows should remain working.
=> [Enhancement]Use single instances for Call objects with the same cId

CHANGELOG.md, Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift, Sources/StreamVideo/CallKit/CallKitService.swift, StreamVideoTests/CallKit/CallKitPushNotificationAdapterTests.swift, StreamVideoTests/CallKit/CallKitServiceTests.swift
CallKitAdapter will dispatch call reporting to the mainActor. That allows accessing callState without additional dispatching (which CallKit dislikes).
- Ring calls on device with the app running, backgrounded, killed. All calls should be reported from CallKit
=> Dispatch CallKit reporting to mainActor

Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideo/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachine+RejectingStage.swift, Sources/StreamVideo/Utils/UUIDProviding/StreamUUIDFactory.swift, Sources/StreamVideo/Utils/Utils.swift, Sources/StreamVideoSwiftUI/CallView/Participants/CallParticipantsInfoViewModel.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/CallKit/CallKitServiceTests.swift, StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift, StreamVideoTests/Utilities/Mocks/MockCXProvider.swift
Ensure that all provided components (CallViewModel, CallKitService) aren't performing joining actions on call events. 
Joining call actions should only be performed from the component that receives the user action.
From a simulator, ring many times an account that's signed in on multiple devices (you can also use a combination of one simulator one physical device). Try any combination between which device accepts/rejects the call and verify what both devices will do.
=> [Fix]Sync call state handling between CallKit and CallViewModel

CHANGELOG.md, DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift, Sources/StreamVideo/CallKit/CallKitService.swift, StreamVideoTests/CallKit/CallKitServiceTests.swift, docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
Allow configuring CallKit supported call types, in order to manage the suffix on the push notification.
=> [Enhancement]Allow configuring CallKit supported call types

Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideoSwiftUITests/CallViewModel_Tests.swift, StreamVideoTests/StreamVideoTestCase.swift, StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift
The revision attempts to fix the recent test failures on `CallViewModel` tests by reducing the need to wait for specific amount of time. Instead it relies on BlockPredicate asserts.
=> [Fix]Async CallViewModel tests

CHANGELOG.md, DemoApp/Sources/Components/AppEnvironment.swift, DemoApp/Sources/Views/CallView/DemoCallContainerView.swift, DemoApp/Sources/Views/Login/DebugMenu.swift, DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/00-ringing.swift, Sources/StreamVideo/Utils/ParticipantAutoLeavePolicy/DefaultParticipantAutoLeavePolicy.swift, Sources/StreamVideo/Utils/ParticipantAutoLeavePolicy/LastParticipantAutoLeavePolicy.swift, Sources/StreamVideo/Utils/ParticipantAutoLeavePolicy/ParticipantAutoLeavePolicy.swift, Sources/StreamVideo/Utils/Publisher+WeakAssign.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift, StreamVideoTests/Utils/ParticipantAutoLeavePolicy/LastParticipantAutoLeavePolicyTests.swift, StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageAcceptedStage_Tests.swift, StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageAcceptingStage_Tests.swift, StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageErrorStage_Tests.swift, StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageIdleStage_Tests.swift, StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageJoinedStage_Tests.swift, StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageJoiningStage_Tests.swift, StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageRejectedStage_Tests.swift, StreamVideoTests/Utils/StateMachine/CallStateMachine/Stages/StreamCallStateMachineStageRejectingStage_Tests.swift, docusaurus/docs/iOS/06-advanced/00-ringing.mdx
Resolves https://github.com/GetStream/ios-issues-tracking/issues/871
Ensure that during a ringing-flow call (incoming or outgoing) when the current user become the only one in the call, they will be automatically kicked out.
As the coordinator seems to require some time to be fully running after a connection has been recovered from an expired token, rather than relying on the participant_left event from the coordinator, we apply a similar logic when the participants update.
|  https://youtu.be/G3Dq48T0ZBk | https://youtu.be/8-bXIMQEdzE |
=> [Enhancement]Participant auto-leave policy implementation

Sources/StreamVideo/Call.swift, Sources/StreamVideo/CallState.swift, Sources/StreamVideo/Controllers/CallController.swift, Sources/StreamVideo/WebRTC/WebRTCClient.swift
We used to update the ownCapabilities for every received event. That was causing an issue where the ownCapabilities will be set back to empty. 
Now, we are observing the ownCapabilities and on every change update every related component.
Try by starting calls, sharing the url to a browser, let them join wait a few seconds and leave the call.
Repeat multiple times without breaks in the middle.
=> [Fix]Disappearing tracks due to lack of capability

Sources/StreamVideo/Call.swift, Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideo/Controllers/CallsController.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift, Sources/StreamVideo/Utils/DisposableBag/DisposableBag.swift, Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift, Sources/StreamVideo/WebRTC/AudioSession.swift, Sources/StreamVideo/WebRTC/PeerConnectionFactory.swift, Sources/StreamVideo/WebRTC/WebRTCClient.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapter.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideoSwiftUI.xcscheme, StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift, StreamVideoTests/IntegrationTests/CallCRUDTests.swift, StreamVideoTests/StreamVideo_Tests.swift, StreamVideoTests/WebRTC/WebRTCClient_Tests.swift
Fix flakiness on LLC and SwiftUI tests.
The main reasons for our failing tests seems to be:
1. Updating cancellables storage from multiple threads
2. Using assert methods that are simply waiting for a specified amount of time (i didn't eliminate all of them as there are many, i just fixed the ones failing very often)
3. RTCVideoTracks need to be set to `enabled = false` before deallocation
The main reasons for our failing tests seems to be:
1. Our AudioSession wrapper needs to disable the RTCAudioSession on deinit
2. PeerConnectionFactory needs to cleanUpSSL on deinit (thanks WebRTC for the [docs](https://github.com/ahoyconference/webrtc-ios/blob/master/WebRTC.framework/Headers/RTCSSLAdapter.h). I also did some cleanup for the factory as it seems it had many unnecessary things on it (e.g …
=> [Fix]Flakey tests on LLC and SwiftUI

DemoApp/Sources/Components/Reactions/ReactionsAdapter.swift, DemoApp/Sources/Components/Router.swift
This PR fixes and issue where reactions aren't visible if the user log out and log back in again.
Login > Logout > Login with another user > join call > reactions should be visible
=> [Fix]Reactions not showing after logging out and back in

.swiftlint.yml, DemoApp/Sources/AppDelegate.swift, DemoApp/Sources/Components/Reactions/ReactionsAdapter.swift, DemoApp/Sources/Components/Router.swift, DemoApp/Sources/Components/Snapshot/LocalParticipantSnapshotViewModel.swift, DemoApp/Sources/DemoApp.swift, DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift, DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift, DemoApp/Sources/Views/CallView/DemoCallsViewModel.swift, DemoApp/Sources/Views/CallsView/CallsViewModel.swift, DemoApp/Sources/Views/Login/LoginViewModel.swift, DemoAppUIKit/SceneDelegate.swift, Mintfile, Sources/StreamVideo/Controllers/CallController.swift, Sources/StreamVideo/Controllers/CallsController.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/WebRTC/PeerConnection.swift, Sources/StreamVideo/WebRTC/SfuMiddleware.swift, Sources/StreamVideo/WebRTC/StreamVideoCaptureHandler.swift, Sources/StreamVideo/WebRTC/WebRTCClient.swift, Sources/StreamVideoSwiftUI/CallView/ParticipantPopoverView.swift, Sources/StreamVideoSwiftUI/CallView/Participants/CallParticipantsInfoViewModel.swift, Sources/StreamVideoSwiftUI/CallView/Participants/InviteParticipantsViewModel.swift, Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, Sources/StreamVideoSwiftUI/CallingViews/PreJoiningViewModel.swift, Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayerViewModel.swift, fastlane/Fastfile
Provide clear error logs for every task that can fail.
SwiftConcurrency tasks swallowing any error that was thrown inside their body outside of an do/catch block ([reference](https://forums.swift.org/t/task-initializer-with-throwing-closure-swallows-error/56066)).
As those errors may produce unwanted behaviour we need to be able at least to track the error. 
This PR does 2 things:
- Integrate SwiftLint into our swift format/lint flow. Currently the only rule that's enabled for swiftLint is the [unhandled_throwing_task](https://realm.github.io/SwiftLint/unhandled_throwing_task.html).
- Fixes all errors produced from SwiftLint by wrapping throwing operations inside tasks into simple do/catch blocks with error logging. Future implementations should consider more extensive error handling.
=> [Enhancement]Error handling inside SwiftConcurrency tasks

CHANGELOG.md, DemoApp/Sources/Examples/Examples.swift, DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/05-incoming-call.swift, Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideo/Models/Extensions/RejectCallRequest+Reason.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/Utils/RejectionReasonProvider/RejectionReasonProvider.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, Sources/StreamVideoSwiftUI/CallingViews/IncomingCallView.swift, Sources/StreamVideoSwiftUI/CallingViews/IncomingCallViewModel.swift, Sources/StreamVideoSwiftUI/CallingViews/iOS13/IncomingCallView_iOS13.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Mock/MockCall.swift, StreamVideoTests/Mock/MockStreamVideo.swift, StreamVideoTests/Utils/RejectionReasonProvider/RejectionReasonProvider_Tests.swift, docusaurus/docs/iOS/05-ui-cookbook/05-incoming-call.mdx
Provide a rejection reason based on this [specification](https://www.notion.so/stream-wiki/Missed-Calls-Spec-4a039b2c97c447688b62842007510456?pvs=4). 
Rejection reason should be added **only** on methods handling explicit user requests (we shouldn't include any rejection reason in methods that respond to call events).
Due to changes the following breaking changes have been introduced as they remove unnecessary code from `IncomingCallViewModel`
- the `hideIncomingCallScreen` property
- the `stopTimer` method.
=> [Enhancement]Provide call rejection reason

Sources/StreamVideoSwiftUI/CallView/ParticipantsGridLayout.swift
Our `HorizontalParticipantsView` sizes the items inside it without taking under consideration the innerItem spacing that the HStack puts between the items. 
This revision fixes that issue by including the total innerItem spacing in the calculation for each item's size.
| ![Simulator Screenshot - iPad Pro (11-inch) (4th generation) (16GB) - 2024-07-15 at 18 34 10](https://github.com/user-attachments/assets/71857aa6-74a3-4620-8469-8f1e523f2d74) | ![Simulator Screenshot - iPad Pro (11-inch) (4th generation) (16GB) - 2024-07-15 at 18 33 25](https://github.com/user-attachments/assets/39619511-1f80-4fd9-9fa3-fc1e814f0746) |
- Join a call with 5 users on …
=> [Fix]Spacing between horizontal participants in gridLayout

fastlane/Fastfile
Resolve https://stream-io.atlassian.net/browse/PBE-5183
Make xcframeworks great again!
- Import `StreamVideo` xcframeworks from `https://github.com/GetStream/stream-video-swift-spm` using branch `test-resolved-spm-issue`
=> Remove StreamVideo module's shadow at xcframeworks' swiftinterfaces

Sources/StreamVideo/CallState.swift
https://stream-io.atlassian.net/browse/PBE-5237
Whenever screensharingSession is non-nil, we ensure that the screenshareTrack is enabled
- Enter - from an iPad - a call with a web user
- Start sharing screen from web
- Move iOS to PiP
- Stop sharing screen from web
- Move iOS to foreground
- Start sharing screen from web
- Screenshare track should be visible
=> [Fix]Screensharing track disappearing when shared second time

DemoApp/Sources/Views/Login/DebugMenu.swift
For now our Debug menu doesn't set correctly the call expiration value as it always default to the `.custom(10)`.
=> [Fix]Debug menu call expiration not working as expected

CHANGELOG.md, Sources/StreamVideo/CallState.swift, Sources/StreamVideo/Controllers/CallController.swift, Sources/StreamVideo/WebRTC/SfuMiddleware.swift, Sources/StreamVideo/WebRTC/WebRTCClient.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/WebRTC/SFUMiddlewareTests.swift
Resolves https://stream-io.atlassian.net/jira/software/c/projects/PBE/boards/151?selectedIssue=PBE-5756
Provide a consistent way for participants (regular and anonymous) count observation (before/after joining a call).
- Listen and react to the new SFU `call.session_participant_count_updated` event.
=> [Enhancement]Handle participantsCount event

CHANGELOG.md, Sources/StreamVideo/Call.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideoTests/Mock/MockStreamVideo.swift
Allow providing initial callSettings when starting a call (and skipping joining).
=> [Fix]Allow callSettings propagation to CallState

Sources/StreamVideo/Call.swift
This revision allows configuring a Call's initial mic, camera and speaker settings by respecting the provided CallSettings.
=> [Fix]CallSettings propagation to call

DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/15-long-press-to-focus.swift, DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/16-snapshot.swift, DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/17-camera-zoom.swift, Sources/StreamVideo/WebRTC/PeerConnectionFactory.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/CallViewModel_Tests.swift, StreamVideoTests/Controllers/CallController_Tests.swift, StreamVideoTests/IntegrationTests/CallCRUDTests.swift, StreamVideoTests/Mock/CallController_Mock.swift, StreamVideoTests/Mock/WebSocketEngine_Mock.swift, StreamVideoTests/Utils/StateMachine/StreamStateMachine_Tests.swift, StreamVideoTests/WebRTC/SFU/Mocks/MockWebSocketClient.swift, StreamVideoTests/WebRTC/SFU/Mocks/MockWebSocketEngine.swift, StreamVideoTests/WebRTC/SFU/SFUAdapter_Tests.swift, StreamVideoTests/WebRTC/SFU/SFUMiddleware_Tests.swift, StreamVideoTests/WebRTC/SFUMiddlewareTests.swift, StreamVideoTests/WebRTC/WebRTCStatsReporter_Tests.swift, docusaurus/docs/iOS/05-ui-cookbook/15-long-press-to-focus.mdx, docusaurus/docs/iOS/05-ui-cookbook/16-snapshot.mdx, docusaurus/docs/iOS/05-ui-cookbook/17-camera-zoom.mdx
This revision tries to bring most of Tests back online in order to provide status visibility on the reconnection-v2 branch.
=> [Fix]Failing tests

Sources/StreamVideoSwiftUI/CallViewModel.swift
Resolves https://stream-io.atlassian.net/browse/PBE-5902
=> [Fix]ringing call issue

CHANGELOG.md, Sources/StreamVideo/Utils/Sorting.swift, StreamVideoTests/Utils/Sorting_Tests.swift
Align participants ordering with [React](https://github.com/GetStream/stream-video-js/blob/fea00ff0ff3984e3ab29706355f98804151734a7/packages/client/src/sorting/presets.ts#L43).
Combine participant comparators to provide a more stable (less jumpy) sorting.
- Join a call with 4 participants
- Have all of them talking while the dominanSpeaker is the one on the fourth position
- When the dominantSpeaker starts speaking (and become dominant) their tile shouldn't move to the first position.
=> [Improve]Default participants ordering

Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Connected.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Connecting.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Disconnected.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+FastReconnected.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+FastReconnecting.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrated.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrating.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Rejoining.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Stage.swift
Resolves https://stream-io.atlassian.net/browse/PBE-5901
When connection is lost there where flows that would result in ending the call rather than reconnecting it. This revision fixes those flows and always disconnect rather than leaving the call.
- Enter a call
- Trigger a migration
- Once migration is done enable airplane mode on your device
- Wait a couple seconds and disable it
- Call should reconnect
=> Disconnect rather than error stage

CHANGELOG.md, DemoApp/Sources/Components/Router.swift, Sources/StreamVideo/StreamVideo.swift
Even though `connectUser` isn't supposed to be called for `anonymous`, it seems that we are calling it anyway (but ignoring the error). This revision checks user type and avoids calling connectUser for `anonymous`.
=> [Fix]MissingPermission error thrown when connectUser shouldn't be called

Sources/StreamVideo/Call.swift, Sources/StreamVideo/Controllers/CallController.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Connecting.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrated.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Rejoining.swift, Sources/StreamVideo/WebRTC/v2/WebRTCAuthenticator.swift, Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift, StreamVideoTests/Call/Call_Tests.swift, StreamVideoTests/Mock/CallController_Mock.swift, StreamVideoTests/Mock/MockCallAuthenticator.swift, StreamVideoTests/Mock/MockWebRTCAuthenticator.swift, StreamVideoTests/Mock/MockWebRTCCoordinatorStack.swift, StreamVideoTests/WebRTC/SFU/SFUEventAdapter_Tests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_CleanUpStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_ConnectingStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_DisconnectedStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_FastReconnectingStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoinedStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoiningStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_LeavingStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_MigratedStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_MigratingStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_RejoiningStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/WebRTCCoordinator_StateMachineTests.swift, StreamVideoTests/WebRTC/v2/WebRTCAuthenticator_Tests.swift, StreamVideoTests/WebRTC/v2/WebRTCCoorindator_Tests.swift, StreamVideoTests/WebRTC/v2/WebRTCJoinRequestFactory_Tests.swift, StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
=> [Fix]Pass all available parameters to connect

Sources/StreamVideo/Controllers/CallController.swift, Sources/StreamVideo/WebRTC/v2/WebRTCCoordinatorProviding.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Call/Call_Tests.swift, StreamVideoTests/Controllers/CallController_Tests.swift, StreamVideoTests/Mock/MockWebRTCCoordinatorFactory.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_ConnectingStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoinedStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_LeavingStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_MigratedStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_MigratingStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_RejoiningStageTests.swift, StreamVideoTests/WebRTC/v2/WebRTCJoinRequestFactory_Tests.swift, StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
=> Reenable Callcontroller tests

CHANGELOG.md, Sources/StreamVideo/Utils/DeviceOrientation/StreamDeviceOrientationAdapter.swift, Sources/StreamVideo/WebRTC/VideoCapturing/StreamVideoCaptureHandler.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift, StreamVideoTests/Mock/MockRTCVideoCapturerDelegate.swift, StreamVideoTests/Utilities/Extensions/CVPixelBuffer+Convenience.swift, StreamVideoTests/WebRTC/VideoCapturing/StreamVideoCaptureHandler_Tests.swift
Resolves https://stream-io.atlassian.net/browse/PBE-6062
Probably, due to the re-creation of the capturer after a reconnection, orientation changes don't propagate correctly, causing the local track to appear disoriented.
We are moving to `StreamVideo`, the `StreamDeviceOrientationAdapter` and update the `StreamDeviceOrientation` cases to be more informative. We then update the `StreamVideoCaptureHandler` to rely on the `StreamDeviceOrientationAdapter` rather than on notifications. In that way we maintain a centralised storage for orientation between `StreamVideo` & `StreamVideoSwiftUI`.
⚠️ Breaking Changes ⚠️ 
- The `StreamDeviceOrientation` values now are `.portrait(isUpsideDown: Bool)` & `.landscape(isLeft: Bool)`.
=> [Fix]Track orientation issue

Sources/StreamVideo/WebRTC/v2/PeerConnection/StreamRTCPeerConnection.swift
Resolves the issue where UI may freeze after multiple reconnections.
- On an old device
- Join a call
- Perform migrations one after another
- UI should never freeze
=> [Fix]UI freeze due to access on ghost tracks

Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+CleanUp.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Connecting.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+FastReconnecting.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Leaving.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrated.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrating.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Rejoining.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Stage.swift, StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift, StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoinedStageTests.swift
Resolves an issue where the call may get disconnected.
=> [Fix]Cancel running tasks on stages when transitioning away

Sources/StreamVideo/Utils/DisposableBag/DisposableBag.swift, Sources/StreamVideo/WebRTC/v2/SFU/SFUEventAdapter.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrating.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Rejoining.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_MigratingStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_RejoiningStageTests.swift
Reduce the amount of unnecessary UI updates during a reconnection.
=> Stop SFU event observation during reconnection

fastlane/Fastfile
- Extract `merge_main_to_develop` to an indie lane to be able to run it locally
- Trigger `release_publish.yml` workflow via `gh` instead of `push` event that did not work
=> [CI] Improvements

Sources/StreamVideo/Utils/ThermalStateObserver.swift, Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/VideoCapturePolicy/VideoCapturePolicy.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/CallView/VideoRenderer_Tests.swift, StreamVideoTests/Controllers/CallController_Tests.swift, StreamVideoTests/Mock/MockThermalStateObserver.swift, StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/VideoCapturePolicy/AdaptiveVideoCapturePolicy_tests.swift, StreamVideoTests/WebRTC/v2/WebRTCCoorindator_Tests.swift, StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Provide stricter for adapting the video capturing quality.
On low end devices or when a device is under thermal stress, we will be activating the adaptive capture quality policy, which will ensure that the capturing video frames are matching the highest quality that SFU has instruct us to send. 
The reason for the limiting criteria, is to avoid a blinking that occurs every time the quality changes, on devices that don't really need to change capturing quality (as it doesn't heavily affect their performance).
=> [Fix]Capture quality adaptive policy criteria

Sources/StreamVideo/Models/Extensions/Stream_Video_Sfu_Models_AppleThermalState+Convenience.swift, Sources/StreamVideo/Utils/Logger/Logger.swift, Sources/StreamVideo/Utils/ThermalStateObserver.swift, Sources/StreamVideo/WebRTC/v2/SFU/SFUAdapter.swift, Sources/StreamVideo/WebRTC/v2/WebRTCStatsReporter.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/WebRTC/SFU/SFUAdapter_Tests.swift, StreamVideoTests/WebRTC/v2/WebRTCStatsReporter_Tests.swift
Provide improved logging capabilities to the SFU but sending the device's ThermalState in the call session stats.
=> [Feature]Report thermal state to SFU

Sources/StreamVideo/WebRTC/WebRTCEvents.swift, Sources/StreamVideo/protobuf/sfu/event/events.pb.swift, StreamVideo.xcodeproj/project.pbxproj
=> Updated the protobufs for codec negotiation

CHANGELOG.md, Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift, Sources/StreamVideo/WebRTC/v2/WebRTCConfiguration.swift, StreamVideoTests/Mock/MockRTCPeerConnectionCoordinator.swift, StreamVideoTests/WebRTC/v2/IntegrationTests/WebRTCIntegrationTests.swift, StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift, StreamVideoTests/WebRTC/v2/WebRTCConfiguration_Tests.swift
Resolves https://stream-io.atlassian.net/browse/PBE-6301
In some cases, a race condition was hit, where Publisher setUp hasn't completed when the negotiation was executing. That resulted in SetPublisherRequest tracks being empty.
Before negotiation, we add a small expectation (setUp must complete before proceeding) and allowing a 2 seconds waiting time for it.
=> [Fix]SetPublisher track setUp race condition

Sources/StreamVideo/WebRTC/v2/SFU/SFUAdapter.swift, Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift, StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Resolves https://stream-io.atlassian.net/browse/PBE-6305
In some cases we noticed in backend logs that iOS devices connect with empty sessionIds. Even though we haven't been able to reproduce it, this revision attempts to eliminate most code paths that set the sessionId to an empty string.
=> [Fix]Empty session ids during livestream

CHANGELOG.md, Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideoSwiftUI/Utils/ToastView.swift, StreamVideoTests/CallKit/CallKitServiceTests.swift
CallKit integration provided from the SDK now supports syncing of the microphone mute state between CallKit and the SDK.
- Lock your device and have another user call you.
- Answer the phone from the lock screen
- Mute/Unmute from the lockscreen
- Tap the bottom left icon to navigate to the app
- Verify that the in-app muted state matches the one from CallKit.
=> [Enhancement]CallKit handling mute

Sources/StreamVideo/Utils/Atomic.swift, Sources/StreamVideo/Utils/Queues/LockQueuing.swift, Sources/StreamVideo/Utils/Queues/RecursiveQueue.swift, Sources/StreamVideo/Utils/Queues/UnfairQueue.swift, Sources/StreamVideo/WebSockets/Client/RetryStrategy.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Utils/Queues/RecursiveQueueTests.swift, StreamVideoTests/Utils/Queues/UnfairQueueTests.swift, StreamVideoTests/WebSockets/Client/DefaultRetryStrategyTests.swift
Improve our locking mechanisms (used to ensure thread-safe access) and add tests to verify stability.
This revision is attempting to align our locking mechanisms (under a single interface) while extending the Atomic property wrapper to be configured with the desired mechanism based on the requirements.
- A `LockQueueing` protocol that will be used as the identifying interface between our locking mechanisms.
- The existing `UnfairQueue` conforms to the new `LockQueueing` protocol.
- A new `RecursiveQueue` that uses a `NSRecursiveLock` underneath and conforms to `LockQueueing`.
- An update on the `Atomic` property wrapper that can now be configured with the desired mechanism.
- Added tests that ensure concurrentAccess and deadlock impossibility.
=> [Improvement]Locking mechanisms and Atomic property wrapper

Sources/StreamVideo/StreamVideo.swift
The path that produces the warning isn't in use as it's covered on the first if statement.
=> [Fix]Compiler warning on StreamVideo

CHANGELOG.md, Sources/StreamVideoSwiftUI/Utils/ReusePool.swift, Sources/StreamVideoSwiftUI/Utils/VideoRendererPool/VideoRendererPool.swift, StreamVideoSwiftUITests/Utils/ReusePool_Tests.swift
Resolves https://linear.app/stream/issue/IOS-494/[alfagift]video-track-appears-stretched-when-the-first-join-livestream
In some cases it appears that the VideoRenderer doesn't respect the provided contentMode and prefers `scaleToFill`.
This revision disables the VideoRendererReusePool until further investigation to understand why it causes this weird behaviour.
|  Before  |  After   |
| -------- | -------- |
| <video src="https://github.com/user-attachments/assets/39a0e056-3287-4d44-85ef-176fc97b982f"/> | <video src="https://github.com/user-attachments/assets/db040611-0411-42fe-8805-6b1205fbf824"/> |
Join multiple livestreams one after another.
=> [Fix]Frame scaled to fill without respecting content mode

DemoApp/Sources/Views/StatsView/DemoStatsView.swift, Sources/StreamVideo/CallState.swift
=> [Fix]Demo stats formula for publishing bitrate

Sources/StreamVideo/WebRTC/v2/SFU/Extensions/Stream_Video_Sfu_Event_SfuEvent.OneOf_EventPayload+Payload.swift, Sources/StreamVideo/WebSockets/Events/Event.swift, Sources/StreamVideo/protobuf/sfu/event/events.pb.swift, Sources/StreamVideo/protobuf/sfu/models/models.pb.swift, Sources/StreamVideo/protobuf/sfu/signal_rpc/signal.pb.swift, StreamVideoTests/Utilities/Dummy/Stream_Video_Sfu_Models_Codec+Dummy.swift
=> Generated code for reporting connection times and code preference

.github/workflows/release-publish.yml
Example: https://getstream.slack.com/archives/CRML30N0H/p1731669961930409
=> [CI] Add reminder about last release step

DemoApp/Sources/Components/AppEnvironment.swift, DemoApp/Sources/DemoApp.swift, DemoApp/Sources/ViewModifiers/CallModifier/DemoCallModifier.swift, DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift, DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift, DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift, DemoApp/Sources/Views/CallView/DemoCallContainerView.swift, DemoApp/Sources/Views/Login/DebugMenu.swift, Sources/StreamVideo/CallState.swift, Sources/StreamVideo/Utils/Sorting.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayer.swift
Allow starting/joining livestreams from the Demo app
| Scenario | Demo |
| -------- | ---- |
| Starting a Livestream |  <video src="https://github.com/user-attachments/assets/0a3320f2-7ddd-447d-b2cf-2b5d6422dea8"/>  |
| Joining a livestream with an ID | <video src="https://github.com/user-attachments/assets/dffc7852-c9a8-4590-bb56-f7122b4d1047"/> | 
| Joining a livestream with url | Just paste any call url with the `type` query parameter set to `livestream` |
=> [PBE-0] support livestream

CHANGELOG.md, DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift, Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift, StreamVideoTests/CallKit/CallKitPushNotificationAdapterTests.swift
Provide a consistent mechanism for consumers of `CallKitAdapter` to remove devices for a user account.
Docs update PR: [here](https://github.com/GetStream/docs-content/pull/44)
=> [Fix]Update deviceToken to empty once unregister void notifications

Sources/StreamVideo/WebRTC/v2/SFU/Extensions/Stream_Video_Sfu_Event_SfuEvent.OneOf_EventPayload+Payload.swift, Sources/StreamVideo/WebSockets/Events/Event.swift, Sources/StreamVideo/protobuf/sfu/event/events.pb.swift, Sources/StreamVideo/protobuf/sfu/models/models.pb.swift
=> Generated new protobufs for codec negotiation

Sources/StreamVideo/WebRTC/v2/SFU/Extensions/Stream_Video_Sfu_Event_SfuEvent.OneOf_EventPayload+Payload.swift, Sources/StreamVideo/WebSockets/Events/Event.swift, Sources/StreamVideo/protobuf/sfu/event/events.pb.swift, Sources/StreamVideo/protobuf/sfu/models/models.pb.swift
=> Generated updated code for codec negotiation

CHANGELOG.md, DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift, DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift, Sources/StreamVideo/CallKit/AvailabilityPolicy/CallKitAlwaysAvailabilityPolicy.swift, Sources/StreamVideo/CallKit/AvailabilityPolicy/CallKitAvailabilityPolicy.swift, Sources/StreamVideo/CallKit/AvailabilityPolicy/CallKitAvailabilityPolicyProtocol.swift, Sources/StreamVideo/CallKit/AvailabilityPolicy/CallKitRegionBasedAvailabilityPolicy.swift, Sources/StreamVideo/CallKit/CallKitAdapter.swift, Sources/StreamVideo/Utils/LocaleProvider/StreamLocaleProvider.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/CallKit/AvailabilityPolicy/CallKitRegionBasedAvailabilityPolicy.swift
Resolves https://linear.app/stream/issue/IOS-551/disable-callkit-in-china-by-default
Provide a consistent and easy way for CallKit to be enabled/disabled based on availability rules (predefined and custom).
The SDK by default provides 2 policies:
- `always`: CallKit will be marked as available in every case
- `regionBased`: CallKit will be marked as unavailable in China region (as identifier by Locale identifiers "CN" and "CHN").
=> [Feature]Introduce CallKit availability policies

CHANGELOG.md, Sources/StreamVideo/Utils/Sorting.swift, StreamVideoTests/Utils/Sorting_Tests.swift
Resolves IOS-499
The revision fixes an issue where the dominant speaker doesn't become the visible track when changing, in fullscreen layout and PictureInPicture.
- Join a call with 2 other participants
- Either change the layout to fullscreen or move to the background (in order to active PiP)
- Make the other users talk in order to change the dominant speaker
- The dominant participant should be visible (and changing) in every case
=> [Fix]Sorting comparators for fullscreen layout and PiP

Sources/StreamVideo/WebRTC/v2/SFU/SFUAdapter.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoiningStageTests.swift
Resolves https://linear.app/stream/issue/IOS-585/report-connection-times-to-the-sfu
Report join call telemetry including join strategy and duration. (React reference [PR](https://github.com/GetStream/stream-video-js/pull/1574/files))
=> [Feature]Report join call telemetry

fastlane/Fastfile
Removing `!` ensures that if there is no `-SNAPSHOT` postfix it won’t clean up the file.
=> [CI] Fix release script

Sources/StreamVideo/protobuf/sfu/event/events.pb.swift, Sources/StreamVideo/protobuf/sfu/models/models.pb.swift
=> Added preferred subscribe options

Sources/StreamVideo/Errors/Errors.swift, Sources/StreamVideo/Utils/AudioSession/StreamAudioSessionAdapter.swift, Sources/StreamVideo/Utils/Logger/Array+Logger.swift, Sources/StreamVideo/Utils/Logger/Logger.swift, Sources/StreamVideo/Utils/Logger/Publisher+Logger.swift, Sources/StreamVideo/Utils/StateMachine/Publisher+NextValue.swift, Sources/StreamVideo/Utils/Unwrap/Unwrap.swift, Sources/StreamVideo/WebRTC/v2/SFU/SFUAdapter.swift, Sources/StreamVideo/WebRTC/v2/WebRTCJoinRequestFactory.swift, Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift, Sources/StreamVideo/WebSockets/Events/JsonEventDecoder.swift
By reducing logs size we attempt to reduce the SDK size.
`#file` in Swift 5 embeds `#filePath` while in Swift 6 it embeds `#fileID`. From Apple's [documentation](https://developer.apple.com/documentation/swift/filepath()#overview) for `#filePath` we get this:
```
Because #fileID doesn’t embed the full path to the source file, unlike #filePath, it gives you better privacy and reduces the size of the compiled binary. Avoid using #filePath outside of tests, build scripts, or other code that doesn’t become part of the shipping program.
```
Other users also report same behaviour [here](https://x.com/KyleSwifter/status/1868562829932150839)
Update all references in Source, to `#fileID`
=> [Fix]Replace `#file` to `#fileID`

CHANGELOG.md, Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift, StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
https://linear.app/stream/issue/IOS-651/[video]stop-videocapturer-and-screensharecapturer-when-call-ends-and
On Call cleanUp we should be stopping all video and screenShare capturers. Without doing that, we end up in the `Call ended screen` and the camera access system indicator remain on.
=> [Fix]CleanUp active videoCapturing and screenSharing sessions

StreamVideoTests/Mock/MockRTCRtpCodecCapability.swift, StreamVideoTests/Mock/MockRTCRtpEncodingParameters.swift
Keypaths on iOS 15 seems to be unable to convert to String values, making our `Mockable` implementation fail. For those cases where this will be happening we can simply override the `propertyKey` function on our `Mockable` instance in order to provide correct mapping for each keyPath.
=> [Fix]Cron checks failing on iOS 15

DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
When parsing Legacy URLs while the current DemoApp Environment is Pronto, rather than triggering an environment switch, proceed in Pronto.
=> [Fix]Legacy URL parsing pointing to Pronto

CHANGELOG.md, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideoSwiftUITests/CallViewModel_Tests.swift
Resolves https://linear.app/stream/issue/IOS-673/[support]user-accepts-ringing-call-in-one-device-in-app-incoming
When a user accepts a ringing call from one device, on all their other devices correctly dismiss CallKit push notification but they do not update CallViewModel's internal state, resulting in the in-app incoming call to remain on screen.
- Have a user login on two different devices (and keep the app in the foreground)
- Have another user ring the user from the first step
- Both devices should present CallKit push notification and in-app incoming call
- Accept the call on one device
- The other device, should dismiss CallKit push notification and in-app incoming call screen.
=> [Fix]Accepting call on another device will sync state with CallViewModel

DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift, Sources/StreamVideo/Call.swift, Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift, Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, Sources/StreamVideoSwiftUI/Models/CallEventsHandler.swift, Sources/StreamVideoSwiftUI/Models/IncomingCall.swift, StreamVideoSwiftUITests/CallingViews/IncomingCallView_Tests.swift, StreamVideoTests/CallKit/CallKitPushNotificationAdapterTests.swift, StreamVideoTests/CallKit/CallKitServiceTests.swift, StreamVideoTests/Utilities/Mocks/MockCallKitService.swift
By handling the `video` property on the VoIP push notification we can inform CallKit so the call will reported with correct suffix (video/audio)
=> [Enhancement]Handle video property on VoIP push notification

DemoApp/Sources/Components/AppState.swift, DemoApp/Sources/Components/MemoryLogDestination/OSLogDestination.swift, DemoApp/Sources/Extensions/DemoApp+Sentry.swift, Sources/StreamVideo/Errors/Errors.swift, Sources/StreamVideo/OpenApi/generated/Models/APIError.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/Utils/Logger/Logger.swift, Sources/StreamVideo/Utils/ReflectiveStringConvertible/ReflectiveStringConvertible.swift
Provide better error logging while improving consistency and error visibility.
Extending `ReflectiveStingConvertible` and conforming main error objects to it.
=> [Enhancement]Improve Error logging

Sources/StreamVideo/WebSockets/Client/URLSessionWebSocketEngine.swift
By checking if the webSocket task is active we ensure that we only process the events (and messages) that really can be processed.
=> [Fix]Misleading error logs when leaving a call

DemoApp/Sources/Components/AppState.swift, DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift, DemoApp/Sources/Models/TokenResponse.swift, Sources/StreamVideo/Utils/Logger/Logger.swift, Sources/StreamVideo/WebSockets/Client/URLSessionWebSocketEngine.swift
=> [Enhancement]Small improvements in logs

DemoApp/Sources/Components/MemoryLogDestination/OSLogDestination.swift, Sources/StreamVideo/CallKit/CallKitPushNotificationAdapter.swift, Sources/StreamVideo/CallKit/CallKitService.swift
Due to the recent changes of Swift 6 Migration, CallKit reporting was changed to async operation. Unfortunately, CallKit expects call reporting to happen synchronously from the moment the PushNotification has been received. ([note](https://developer.apple.com/documentation/pushkit/pkpushregistrydelegate/pushregistry(_:didreceiveincomingpushwith:for:completion:)))
=> [Swift6 Migration]Fix CallKit crash

StreamVideoTests/Utils/AudioSession/StreamRTCAudioSession_Tests.swift
https://linear.app/stream/issue/IOS-712/flakey-test-currentroute-returnssourcevalue
=> [Fix]Failing tests in Xcode 15 iOS 15.5

CHANGELOG.md, Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift
Resolves https://linear.app/stream/issue/IOS-730/[khealth]crash-on-microphonechecker
Resolve a race condition that could make the MicrophoneChecker crash.
=> [Fix]SerialQueue processing for MicrophoneChecker operations

CHANGELOG.md, DemoApp/Sources/ViewModifiers/MoreControls/DemoNoiseCancellationButtonView.swift, Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
Resolves https://linear.app/stream/issue/IOS-731/noisecancellation-cannot-be-activated
NoiseCancellation activation requires an activeCall from StreamVideo client. When the value hasn't been updated we should defer the execution until we have a value.
=> [Fix]NoiseCancellation activating step

DemoApp/Sources/Components/MemoryLogDestination/OSLogDestination.swift, Sources/StreamVideo/Call.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
This revision ensures:
1. NoiseCancellation is always enabled on the correct call, whenever its required
2. NoiseCancellation state will be reset after leaving a call
- Join a call
- Check that noise cancellation is active
- Leave the call
- Join another call (or the same one)
- Check that noise cancellation is active
=> [Fix]NoiseCancellation activation (part 2)

CHANGELOG.md, Sources/StreamVideo/Controllers/CallController.swift, Sources/StreamVideo/Errors/Errors.swift, Sources/StreamVideo/OpenApi/generated/Models/APIError.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Blocked.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Stage.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Controllers/CallController_Tests.swift, StreamVideoTests/Utils/StateMachine/StreamStateMachine_Tests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_BlockedStageTests.swift
Resolves https://linear.app/stream/issue/IOS-740/[video]handle-blocked-user-correctly
By default, blocked users are being kicked out from the call (by the backend). If a user somehow manage to find themselves in the call again, we add an additional check that is based on the blockIds from the joinResponse. If the user id is in there, we are making them leave the call.
=> [Improvement]Handle blocked users

DemoApp/Sources/Components/MemoryLogDestination/MemoryLogViewer.swift, DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift, Sources/StreamVideo/Call.swift, Sources/StreamVideo/Controllers/CallController.swift, Sources/StreamVideo/Utils/StateMachine/CallStateMachine/StreamCallStateMachine.swift, Sources/StreamVideo/Utils/StateMachine/StreamStateMachine.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Connecting.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Disconnected.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/WebRTCCoordinator+StateMachine.swift, Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Controllers/CallController_Tests.swift, StreamVideoTests/Utils/StateMachine/CallStateMachine/StreamCallStateMachine_Tests.swift, StreamVideoTests/Utils/StateMachine/StreamStateMachine_Tests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_DisconnectedStageTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/WebRTCCoordinator_StateMachineTests.swift
Resolves 
- https://linear.app/stream/issue/IOS-741/[investigate]video-not-recovering-when-using-link-conditioner
- https://linear.app/stream/issue/IOS-738/[video]investigate-reconnection-on-ios
Relax StateMachine transitions, so that on invalid transitions rather than erroring we just print a warning. We still do not fulfil the invalid transition!
=> [Fix]Make StateMachine invalid transitions warnings rather than errors

fastlane/Fastfile
It used to remove all the `SwiftUICore.View` entries, but it turned out there are also `SwiftUICore.EmptyView`, `SwiftUICore.Font`, etc...
=> [CI] Remove all the SwiftUICore module shadows in xcframeworks

CHANGELOG.md, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift, Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoiningStageTests.swift, StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
When a migration or reconnection is in progress, then the local participant appears twice in the call screen (two video tiles) until we receive the finalised update from the SFU. With this change we filter out any participant that matches the sessionId of the session from which we rejoin or migrate from.
- Join a call with someone else
- Open the More Menu > Reconnect > Rejoin/Migrate
- During the process the current user shouldn't appear more than once in the Participants View
=> [Fix]Avoid showing the current user twice during a migration/reconnection

CHANGELOG.md, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joining.swift, Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoiningStageTests.swift, StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Duplicate of https://github.com/GetStream/stream-video-swift/pull/731
=> [Fix]Avoid current user showing up as duplicated during reconnection and migration

Sources/StreamVideo/Call.swift
This revision fixes the errors showing when in a user enters the lobby and we try to activate transcriptions, closed captions and noise-cancellation. Those operations are failing because there is no active-call-session yet. We now tie those operations to the session, once there is an active-call-session we trigger them.
=> [Fix]Bind transcription and noise cancelling to session

SwiftUIDemoAppUITests/Robots/UserRobot+Asserts.swift, SwiftUIDemoAppUITests/Robots/UserRobot.swift, SwiftUIDemoAppUITests/Tests/CallViewsTests.swift
Resolves https://linear.app/stream/issue/IOS-766/disable-gleap-for-e2e-tests
This revision fixes an issue that was affecting E2E tests. The usage of `firstMatch` was causing non-ending loops of looking for the element and couldn't find it while it was there.
=> [Fix]E2E main thread access issue

CHANGELOG.md, Sources/StreamVideo/WebRTC/v2/WebRTCAuthenticator.swift, StreamVideoTests/WebRTC/v2/WebRTCAuthenticator_Tests.swift
Resolves https://linear.app/stream/issue/IOS-778/livestream-viewer-attempts-to-publish-audio-when-not-capability-exist
This revision fixes an issue that only applying CallSettings (either the provided ones or from the dashboard) when the call was created and joined. The issue was discovered when testing with Livestream viewers who are only joining the call (not creating it).
=> [Fix]CallSettings not respected when `create=false`

CHANGELOG.md, Package.swift, StreamVideo.xcodeproj/project.pbxproj
Resolves https://linear.app/stream/issue/IOS-781/update-webrtc-version-to-1256422066
=> Update webrtc version to 125.6422.066

Sources/StreamVideo/CallKit/CallKitService.swift
Resolves https://linear.app/stream/issue/IOS-784/[blink]callkit-end-call-doesnt-leave-the-call-when-device-is-locked
When the device is locked and the user accepts a call via CallKit, once they press the end call button the participant isn't removed from the call.
- Lock the device (the app can be running or not in the background)
- Ring the device from another device
- Answer using CallKit. Do not unlock the device
- Once you have answered the call, end it
- The participant should be removed from the call
=> [Fix]CallKit end call wasn't completing successfully

CHANGELOG.md, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideoSwiftUITests/CallViewModel_Tests.swift
Resolves https://linear.app/stream/issue/IOS-783/[blink]reset-callsetting-on-callviewmodel-after-call-is-being-left
This revision removes the `CallSettings` propagation, between calls, when using the `CallViewModel`.
=> [Enhancement]Allow resetting local call settings

CHANGELOG.md, DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift, Package.swift, Sources/StreamVideoSwiftUI/Resource.swift, Sources/StreamVideoSwiftUI/Sounds.swift, Sources/StreamVideoSwiftUI/Utils/CallSoundsPlayer.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/Utils/ResourceTests.swift, StreamVideoSwiftUITests/Utils/Resource_Tests.swift
Resolves https://linear.app/stream/issue/IOS-785/[blink]outgoing-call-sound-not-playing
https://github.com/GetStream/docs-content/pull/291
When using the SDK via SPM, Sound resources aren't playable. There are 2 reasons for that:
- Resources aren't being processed for `StreamVideoSwiftUI`
- In order for the resource to be found we should pass both the name and the extension in the Bundle load call. Specifically we need to pass the values separately and not as a single string value.
Sound resources are now represented by a new struct called `Resource`. The struct conforms to `ExpressibleByStringLiteral` which ensures that existing overrides won't be affected.
The following lines have been added to the `Package.swift`: 
```swift
...
resources: [
.process("Resources")
]
...
```
=> [Fix]Resource loading when used via SPM

CHANGELOG.md, Sources/StreamVideo/CallSettings/SpeakerManager.swift, Sources/StreamVideo/CallState.swift, Sources/StreamVideo/Models/CallSettings.swift, Sources/StreamVideo/Models/Extensions/CallSettingsResponse+SettingsPriority.swift, Sources/StreamVideo/WebRTC/v2/WebRTCAuthenticator.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/CallView/CallControls/Stateless/StatelessAudioOutputIconView_Tests.swift, StreamVideoTests/Models/CallSettingsResponse+SettingsPriorityTests.swift, StreamVideoTests/WebRTC/v2/WebRTCAuthenticator_Tests.swift
Resolves https://linear.app/stream/issue/IOS-796/[blink]speaker-icon-flashing
Dashboard contains the following configurations
This revision ensures that the settings above will be applied with the following priority:
- If camera is on, speaker will be on by default
- If camera is off, and `Speaker on by Default`, speaker will be on
- If camera is off, `Speaker on by Default` is off and default device is speaker, speaker will be on
- Otherwise earpiece will be on
=> [Fix]Respect dashboard audio settings

Sources/StreamVideo/CallState.swift
Resolves https://linear.app/stream/issue/IOS-813/session-participants-event-handling.
Fix duplicated session participants.
=> Fix handling of session join/leave events for existing users

CHANGELOG.md, Sources/StreamVideoSwiftUI/CallViewModel.swift
Resolves https://linear.app/stream/issue/IOS-815/[blink]mute-state-misalignment
Fix an issue that is causing the audio/video state to be misaligned with the server.
=> [Fix]Mute state misalignment

CHANGELOG.md, Sources/StreamVideo/Models/CallSettings.swift, Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSession.CategoryOptions+Convenience.swift, Sources/StreamVideo/Utils/AudioSession/Policies/DefaultAudioSessionPolicy.swift, Sources/StreamVideo/Utils/AudioSession/Policies/OwnCapabilitiesAudioSessionPolicy.swift, Sources/StreamVideo/Utils/AudioSession/StreamAudioSession.swift, Sources/StreamVideo/Utils/StreamAppStateAdapter/StreamAppStateAdapter.swift, Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/Utilities/ApplicationLifecycleVideoMuteAdapter.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureController.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/Utils/StreamAppStateAdapter/StreamAppStateAdapter_Tests.swift, StreamVideoTests/Mock/MockAppStateAdapter.swift, StreamVideoTests/Utils/AudioSession/Extensions/AVAudioSessionCategoryOptions_Tests.swift, StreamVideoTests/Utils/AudioSession/Policies/DefaultAudioSessionPolicyTests.swift, StreamVideoTests/Utils/AudioSession/Policies/OwnCapabilitiesAudioSessionPolicyTests.swift
Resolves https://linear.app/stream/issue/IOS-816/[blink]speaker-turns-off-when-video-is-off
A recent change introduce a regression which is causing the speaker to be disabled when video isn't enabled.
The issue is being caused from two parts:
- Our AudioSession policies where wrong (regression introduced in the #762)
- #762 before introducing the regression was trying to fix an issue that was stopping the user from disabling the speaker in CallKit's screen.
In this revision we are trying to solve those issues once an for all. 
By reverting the changes from #762, we get back to the original issue. Strangely the reason why CallKit doesn't allow the turning off of the speaker is because we are using an override.  For some reason CallKit considers that override a hard override and doesn't …
=> [Fix]AudioSession disabling speaker when video is off

Sources/StreamVideo/Call.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/Utils/StateMachine/Publisher+NextValue.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Call/Call_Tests.swift, StreamVideoTests/IntegrationTests/CallCRUDTests.swift, StreamVideoTests/IntegrationTests/IntegrationTest.swift, StreamVideoTests/Mock/MockStreamVideo.swift, StreamVideoTests/Mock/StreamVideo_Mock.swift
Resolves https://linear.app/stream/issue/IOS-833/[fix]unnecessary-streamvideo-connection-operation-and-resolve
The automatic connection process we have in place, when StreamVideo instance is being created, is unnecessary during tests and in some cases causes flakiness (it also goes through real networking and hits the backend). 
This revision runs the automatic connection process only when not running tests.
=> [Fix]Remove unnecessary operation during tests and fix flakiness

CHANGELOG.md, Sources/StreamVideoSwiftUI/CallViewModel.swift
Resolves https://linear.app/stream/issue/IOS-835/ringing-flow-issues-when-callviewmodel-is-involved
In the scenario where, one Android user calls 1 android user and 1 iOS, if the Android callee rejects the call, iOS (wrongly) will also reject causing the caller also to be dropped from the call.
- Align CallViewModel handleReject logic with CallKitService
- Start the ringing timer from CallKit so CallViewModel can auto-cancel the call.
=> [Fix]Ringing flow issues

Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureStore.swift
Resolves https://linear.app/stream/issue/IOS-836/fix-pictureinpicturestore-thread-access-warning
=> [Fix]Picture-in-Picture store thread access

CHANGELOG.md, DemoApp/Sources/Components/AppEnvironment.swift, DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift, DemoApp/Sources/Views/Login/DebugMenu.swift, DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj, DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/05-proximity-policies.swift, Sources/StreamVideo/Call.swift, Sources/StreamVideo/CallSettings/ProximityManager.swift, Sources/StreamVideo/Utils/CurrentDevice/CurrentDevice.swift, Sources/StreamVideo/Utils/Proximity/Monitor/ProximityMonitor.swift, Sources/StreamVideo/Utils/Proximity/Policies/ProximityPolicy.swift, Sources/StreamVideo/Utils/Proximity/Policies/SpeakerProximityPolicy.swift, Sources/StreamVideo/Utils/Proximity/Policies/VideoProximityPolicy.swift, Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/CallSettings/ProximityManager_Tests.swift, StreamVideoTests/Mock/CurrentDevice+Dummy.swift, StreamVideoTests/Mock/MockCallController.swift, StreamVideoTests/Mock/MockProximityMonitor.swift, StreamVideoTests/Mock/MockProximityPolicy.swift, StreamVideoTests/Utils/Proximity/Monitor/ProximityMonitor_Tests.swift, StreamVideoTests/Utils/Proximity/Policies/SpeakerProximityPolicy_Tests.swift, StreamVideoTests/Utils/Proximity/Policies/VideoProximityPolicy_Tests.swift, StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Resolves https://linear.app/stream/issue/IOS-827/[feature-request]proximity-for-calls
Provide proximity based operations during a call.
- https://github.com/GetStream/docs-content/pull/321
We introduce a new protocol `ProximityPolicy` that can be used to define what will happen when the device's proximity change during a call. You can attach `ProximityPolicy` instances on any Call object.
Out of the box, the SDK ships with the following `ProximityPolicy` implementations:
- `SpeakerProximityPolicy`: If speaker is enabled when proximity changes to `near` the policy will switch to earpiece. It will then restore speaker when proximity changes to `far`.
- `VideoProximityPolicy`: The policy disables all video (remote and local) when proximity changes to `near` and restores everything back when …
=> [Enhancement]Implement proximity policies

CHANGELOG.md, DemoApp/Sources/Views/CallView/DemoSnapshotViewModel.swift, Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessAudioOutputIconView.swift, Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessMicrophoneIconView.swift, Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessSpeakerIconView.swift, Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessToggleCameraIconView.swift, Sources/StreamVideoSwiftUI/CallView/CallControls/Stateless/StatelessVideoIconView.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureController.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureAdapter.swift
Resolves https://linear.app/stream/issue/IOS-839/blink-picture-in-picture-issues
This revisions fixes a few points that seem to be affecting the Picture-in-Picture lifecycle
- Join a call with another user
- Ensure that PiP works
- Leave the Call
- Join another call
- Ensure that PiP still works
=> [Fix]Picture-in-Picture trigger and lifecycle

CHANGELOG.md, Sources/StreamVideoSwiftUI/CallView/CallControls/Stateful/CallControlsView.swift, Sources/StreamVideoSwiftUI/CallingViews/CallConnectingView.swift, StreamVideoSwiftUITests/CallView/CallControls/Stateful/CallControlsView_Tests.swift, StreamVideoSwiftUITests/CallingViews/CallConnectingView_Tests.swift, StreamVideoSwiftUITests/CallingViews/OutgoingCallView_Tests.swift
Resolves https://linear.app/stream/issue/IOS-845/blinkoutgoingcallview-issues
Update OutgoingCallView to receive updates from the `StreamVideo.state.ringingCall` to cover cases where the Call instance may be created remotely (e.g. from the backend).
=> [Fix]Update OutgoingCallScreen from the ringingCall

CHANGELOG.md, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureController.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureEnforcedStopAdapter.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureControllerProtocol.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/Utils/PictureInPicture/MockAVPictureInPictureController.swift, StreamVideoSwiftUITests/Utils/PictureInPicture/PictureInPictureEnforcedStopAdapterTests.swift
Resolves https://linear.app/stream/issue/IOS-847/blinkpicture-in-picture-while-in-foreground
When the app becomes active from the application switcher, Picture-in-Picture remains active. This revision introduces a stopEnforcer that observes the applicationState(foreground/background) in relationship to the Picture-in-Picture active state and when required enforces stopping.
- Join a call with someone else
- Move the app to the background
- Ensure picture-in-picture is active
- Open the application switcher (double tap the home button or swipe from bottom to the middle of the screen)
- Select the app to move it to the foreground
- Ensure picture-in-picture was disabled after the app became active
=> [Fix]Enforce picture-in-picture stop on foreground

CHANGELOG.md, Sources/StreamVideo/Call.swift, Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideo/Controllers/CallController.swift, Sources/StreamVideo/Utils/AudioSession/Policies/DefaultAudioSessionPolicy.swift, Sources/StreamVideo/Utils/AudioSession/Protocols/AVAudioSessionProtocol.swift, Sources/StreamVideo/Utils/AudioSession/StreamAudioSession.swift, Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/CallKit/CallKitServiceTests.swift, StreamVideoTests/Mock/MockAVAudioSession.swift, StreamVideoTests/Mock/MockCall.swift, StreamVideoTests/Utils/AudioSession/Policies/DefaultAudioSessionPolicyTests.swift, StreamVideoTests/Utils/AudioSession/StreamAudioSession_Tests.swift
Resolves https://linear.app/stream/issue/IOS-859/blinkcallkit-audiosession-speaker-state
CallKit reconfigures the AudioSession using a minimum set of configuration. As the SDK also takes control of the AVAudioSession management, align the CallKit AudioSession configuration with the CallSettings during the call.
=> [Fix]CallKit AudioSession speaker sync

CHANGELOG.md, Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift, StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Resolves https://linear.app/stream/issue/IOS-858/bugcallsettings-misalignment-during-reconnections
During reconnections we should maintain CallSettings and published tracks.
=> [Fix]CallSettings during reconnection

CHANGELOG.md, Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
Resolves https://linear.app/stream/issue/IOS-871/break-streamvideo-memory-leak
=> [Fix]Break StreamVideo memory leak

CHANGELOG.md, Sources/StreamVideoSwiftUI/CallViewModel.swift, Sources/StreamVideoUIKit/CallViewController.swift
Resolves https://linear.app/stream/issue/IOS-878/add-teamfield-when-creating-a-call-from-callviewmodel-and
Allow passing the `team` parameter when creating a call from CallViewModel and CallViewController.
=> [Fix]Add team to the CallViewModel and CallViewController

CHANGELOG.md, Sources/StreamVideo/WebRTC/v2/Extensions/Foundation/Publisher+TaskSink.swift, Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift, StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
Resolves https://linear.app/stream/issue/IOS-869/tasksink-causes-occasional-crash-on-microphonechecker
`TaskSink` causes an occasional crash on MicrophoneChecker. This revision attempts to fix this by holding a reference to the input value inside TaskSync and then use the hold value inside the async operation.
=> [Fix]MicrophoneChecker occasional crash

CHANGELOG.md, Sources/StreamVideo/WebRTC/v2/WebRTCAuthenticator.swift
Resolves https://linear.app/stream/issue/IOS-877/avaudiosessionwhen-user-has-connected-an-external-device-and-the-joins
This revision attempts to remove unnecessary changes to audio routes.
When joining a Call, if the user has an external audio device connected, we will ignore the remote `CallSettings.speakerOn = true`.
=> [Fix]Initial CallSetttings and external audio output

CHANGELOG.md, Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideo/Utils/RejectionReasonProvider/RejectionReasonProvider.swift, StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift, StreamVideoTests/CallKit/CallKitServiceTests.swift, StreamVideoTests/Mock/MockCall.swift, StreamVideoTests/Utils/RejectionReasonProvider/RejectionReasonProvider_Tests.swift
Resolves https://linear.app/stream/issue/IOS-876/when-ringing-timeouts-callkit-should-be-reporting-reject-with-reason
CallKit will report correctly the reason `timeout` when the call ringing timeout is reached.
=> [Enhancement]CallKit will report ring timeout as reason when appropriate

DemoApp/Sources/Components/Reactions/ReactionsAdapter.swift, Sources/StreamVideo/Call.swift, Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideo/Controllers/CallsController.swift, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/Utils/ClosedCaptionsAdapter/ClosedCaptionsAdapter.swift, Sources/StreamVideo/WebSockets/Events/WSEventsMiddleware.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideoSwiftUITests/CallingViews/LobbyViewModel_Tests.swift, StreamVideoTests/Call/Call_Tests.swift, StreamVideoTests/Controllers/CallController_Tests.swift, StreamVideoTests/StreamVideo_Tests.swift
AsyncStreams are causing leaks on continuations. This revision attempts to fix that by backing AsyncStream on StreamVideo, by Combine Publishers
| ✅ | Given               | When                                                   | Then                                                                 |
|----|---------------------|--------------------------------------------------------|----------------------------------------------------------------------|
| 🟠 | In a call alone     | I enable the camera                                    | The camera has a flipping animation                                 |
| 🟠 | In a call           | I rotate the device                                    | The app freezes and then kills the phone                            |
| 🟠 | In a call           | I …
=> [Performance]Break async stream memory leaks

Gemfile.lock, fastlane/Fastfile, fastlane/Pluginfile
Resolve https://linear.app/stream/issue/IOS-891
To avoid an issue when AppStore version locks a TestFlight version
|  We used to add a `-SNAPSHOT` postfix to already released version and push it to `develop`.   |  This PR introduces a new approach -  to bump a minor version of an already released version, add a `-SNAPSHOT` postfix and push it to `develop`.  |
One time `bundle install` from this branch (or from develop after this PR is merged) is required to be able to release locally next time.
=> [CI] Bump snapshot version after every release

CHANGELOG.md, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideoSwiftUITests/CallViewModel_Tests.swift, StreamVideoTests/Mock/MockCall.swift, StreamVideoTests/Mock/MockStreamVideo.swift
Resolves https://linear.app/stream/issue/IOS-918/loudspeaker-on-for-caller-when-remote-callsettings-have-speakerfalse
This revision changes the CallViewModel's behaviour when starting a Call with `ring:true`. If no CallSettings have been provided, then the CallViewModel will respect the CallSettings from the dashboard rather than enforcing it's default ones.
=> [Fix]Respect dashboard callSettings for outgoing calls when no local settings provided

CHANGELOG.md, Sources/StreamVideo/StreamVideo.swift, Sources/StreamVideo/Utils/IdleTimerAdapter/IdleTimerAdapter.swift, Sources/StreamVideoSwiftUI/CallView/CallView.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/Utils/IdleTimerAdapter/IdleTimerAdapter_Tests.swift
This PR removes the `UIApplication.shared.isIdleTimerDisabled` handling from UI and makes it an SDK responsibility. That should make UI creation simpler and less error prone.
=> [Enhancement]Remove IdleTimer handling from UI

CHANGELOG.md, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Disconnected.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_DisconnectedStageTests.swift
Resolves https://linear.app/stream/issue/IOS-942/patreonnon-ending-tries-to-join-ended-livestream
The WebRTC state machine stages now respect the `unrecoverable` flag on the APIEError object.
=> [Fix]Reconnection loop when trying to join an ended call without required permissions

Sources/StreamVideo/WebRTC/v2/SFU/Extensions/Stream_Video_Sfu_Event_SfuEvent.OneOf_EventPayload+Payload.swift, Sources/StreamVideo/WebSockets/Events/Event.swift, Sources/StreamVideo/protobuf/sfu/event/events.pb.swift, Sources/StreamVideo/protobuf/sfu/models/models.pb.swift, Sources/StreamVideoSwiftUI/CallViewModel.swift
Part of https://linear.app/stream/issue/IOS-985/pause-video-on-low-bandiwdth.
=> Added events and models for pausing video in low bandwidth

Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideoSwiftUITests/CallViewModel_Tests.swift
Resolves https://linear.app/stream/issue/IOS-995/fixcall-event-overflow
While inCall if user receive a new call, and that call gets ended while the user hasn't accepted/rejected the new call, the user was leaving the active call.
- Ring your device
- While in call ring from your device but in this new call include 3 members
- While the user is in call but sees the CallKit notification, accept the call on the 3rd member
- The 3rd member then triggers an end call
- The user should remain the initially active call
=> [Fix]Call event overflow

DemoApp/Sources/Components/AppEnvironment.swift, DemoApp/Sources/Extensions/DemoApp+Sentry.swift, DemoApp/Sources/Views/Login/DebugMenu.swift, Sources/StreamVideo/Utils/Logger/Logger.swift, Sources/StreamVideo/Utils/Logger/WebRTCLogger.swift, StreamVideo.xcodeproj/project.pbxproj
Surface WebRTC internal logs via the SDK's logger.
Provide a way for integrators to access those logs (if needed). By default they are disabled for the SDK but enabled for the DemoApp.
=> [Enhancement]WebRTC logs via SDK logger

CHANGELOG.md, Sources/StreamVideoSwiftUI/CallViewModel.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoSwiftUITests/CallViewModel_Tests.swift, StreamVideoTests/Mock/MockCall.swift, StreamVideoTests/Mock/MockDefaultAPI.swift
Resolves https://linear.app/stream/issue/IOS-1031/blinkios-ending-outgoing-group-call-when-one-of-the-participants
In cases where the call is being created on the backend and the iOS device relies on it to set the call data correctly, by calling `CallViewModel.startCall` with an empty `members` and `ring = true` array then if the call is rejected by one of the participants then iOS mistakenly will end the call for everyone.
The CallViewModel now observes the `CallState.members` when its `callingState = .outgoing` and `outgoingCallMembers.isEmpty`.
- Create a ringing group call (minimum 3 participants) from the cli where the iOS user will be the creator
- Start the call then on iOS
- Reject the call from one of the other participants
- Call should continue ringing for everyone else
=> [Fix]CallViewModel ending outgoing group call when one of the participants rejects

DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift, Sources/StreamVideoSwiftUI/CallView/ConnectionQualityIndicator.swift, Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift, Sources/StreamVideoSwiftUI/Utils/PaddingsConfig.swift, Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureParticipantModifier.swift, StreamVideo.xcodeproj/project.pbxproj
Resolves https://linear.app/stream/issue/IOS-1065/fix-pip-ui-issues-on-ios-26.
Fix UI issues on PiP on iOS 26.
=> Fix PiP UI issues on iOS 26

CHANGELOG.md, Sources/StreamVideo/Models/CallSettings.swift, Sources/StreamVideo/Utils/AudioSession/RTCAudioStore/Effects/RTCAudioStore+RouteChangeEffect.swift, Sources/StreamVideo/Utils/AudioSession/StreamAudioSessionAdapterDelegate.swift, Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift, Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift, Sources/StreamVideo/WebRTC/v2/WebRTCAuthenticator.swift, Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift, Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift, StreamVideoTests/Controllers/CallController_Tests.swift, StreamVideoTests/Utils/AudioSession/RTCAudioStore/Effects/RouteChangeEffect_Tests.swift, StreamVideoTests/Utils/AudioSession/RTCAudioStore/RTCAudioStore_Tests.swift, StreamVideoTests/Utils/Store/Store_PerformanceTests.swift, StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoinedStageTests.swift, StreamVideoTests/WebRTC/v2/WebRTCCoorindator_Tests.swift, StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
Resolves https://linear.app/stream/issue/IOS-916/videoproximity-doesnt-stop-local-video-and-its-visible-on-remote
This revisions provides improvements in situations that causing CallSettings to update rapidly. With the updates, we can now ensure serial updates for those rapid changes.
`WebRTCStateAdapter` now handles `CallSettings` updates as enqueued operations. In that way every update request will be passed the current CallSettings at the moment and is expected to return the update it needs. In this way we provide step by step updates in CallSettings rather than complete replacements.
- With proximity policies enabled
- Join call
- Move your hand close to the front camera
- Notice that video and speaker should be disabled
- Move your hand away from the front camera
- Video and Speaker …
=> [Fix]CallSettings rapid updates

Sources/StreamVideo/CallKit/CallKitService.swift, Sources/StreamVideo/CallKit/MissingPermissionPolicy/CallKitMissingPermissionPolicy.swift, Sources/StreamVideo/CallKit/MissingPermissionPolicy/CallKitMissingPermissionPolicyProtocol.swift, Sources/StreamVideo/CallKit/MissingPermissionPolicy/Policies/CallKitMissingPermissionPolicy+EndCall.swift, Sources/StreamVideo/CallKit/MissingPermissionPolicy/Policies/CallKitMissingPermissionPolicy+NoOp.swift, StreamVideo.xcodeproj/project.pbxproj, StreamVideoTests/CallKit/CallKitServiceTests.swift, StreamVideoTests/CallKit/MissingPermissionPolicy/CallKitMissingPermissionPolicy_Tests.swift, StreamVideoTests/CallKit/MissingPermissionPolicy/Policies/CallKitMissingPermissionPolicy_EndCallTests.swift
Enhances the user experience when using CallKit and the user hasn't granted the microphone permission.
This revision adds 2 mechanisms to support the scenario where a user receives a VoIP, while the app isn't running or the screen is locked, and the answered call remains in CallKit:
- The CallKitService now is aware of the CallSettings in the active call. When the audioOn setting changes the service updates the CallKit mute button accordingly. Additionally, if the microphone permission isn't granted the services fails any user action to unmute.
- We now expose MissingPermissionPolicy for CallKit, which can be configured with one of the following 2 options:
- - `.none`: There is no special handling happening when the microphone permission is missing.
- - `.endCall`: The call will end, …
=> [Enhancement]Callkit missing recording permission

Sources/StreamVideo/WebRTC/v2/WebRTCJoinRequestFactory.swift, StreamVideoTests/WebRTC/v2/WebRTCJoinRequestFactory_Tests.swift
Resolves https://linear.app/stream/issue/IOS-1167/send-unified-session-id-on-joinrequest
=> [Enhancement]Add unified session id to join request

CHANGELOG.md, Sources/StreamVideo/WebRTC/v2/WebRTCPermissionsAdapter.swift, Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
Resolves https://linear.app/stream/issue/IOS-1137/excess-permissions-prompts-after-the-call-is-ended
This PR addresses the permissions prompts (mic and/or camera) that may show up even when the call has been cleaned up (but the feedback screen is still visible).
- Uninstall the app
- Install and login with a user
- Let the app running and lock the screen
- Receive a call and accept
- while on Callkit, terminate the call
- After call termination unlock the screen and the app will present with the feedback screen on but now prompts
=> [Fix]Stop permission prompts on call cleanup
