GetStream/stream-video-swift

- DemoApp/AppState.swift
- DemoApp/CallView.swift
- DemoApp/CustomWaitingUserView.swift
- DemoApp/DeeplinkAdapter.swift
- DemoApp/DemoApp-Debug.entitlements
- DemoApp/DemoApp.entitlements
- DemoApp/DemoAppUtils.swift
- DemoApp/HomeView.swift
- DemoApp/Info.plist
- DemoApp/StreamCallingView.swift
- DemoApp/StreamVideoSwiftUIApp+Sentry.swift
- DemoApp/StreamVideoSwiftUIApp.swift
- DemoApp/TokenService.swift
- Sources/StreamVideo/HTTPClient/HTTPClient.swift
- Sources/StreamVideo/Models/PushNotificationsConfig.swift
- StreamVideo.xcodeproj/project.pbxproj
Provide parity on deeplink handling between DemoApp and Dogfood
Simulator:
- Run the app
- From terminal execute ```xcrun simctl openurl booted "streamvideo://video?id=<call-id>"```
Device:
- Install the app
- On Safari Paste & Go to ```"streamvideo://video?id=<call-id>"```
> Handle deeplinks from Staging

- docusaurus/docs/iOS/02-tutorials/02-audio-room.mdx
> Add videos

- Sources/StreamVideo/Controllers/PermissionsController.swift
- Sources/StreamVideo/WebRTC/WebRTCClient.swift
- Sources/StreamVideo/WebSockets/Events/CallsMiddleware.swift
> Fix permissionsController and WebRTCClient

- docusaurus/docs/iOS/02-tutorials/02-audio-room.mdx
> Minor changes in AudioRoom tutorial

- Sources/StreamVideo/Call.swift
- Sources/StreamVideo/StreamVideo.swift
- Sources/StreamVideo/Utils/Utils.swift
> Add subscribe to specific event on StreamVideo

- Sources/StreamVideoSwiftUI/CallContainer.swift
- Sources/StreamVideoSwiftUI/CallingViews/iOS13/VideoView_iOS13.swift
- Sources/StreamVideoSwiftUI/Utils/ViewExtensions.swift
> Use the right participantsCount when joining a call (with any auth)

- README.md
> Add hero image to README, with rounded corners and a (very) subtle shadow even.

- docusaurus/docs/iOS/06-advanced/06-events.mdx
> Update Events doc page

- Sources/StreamVideo/Call.swift
- Sources/StreamVideo/CallState.swift
- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/Models/CallParticipant.swift
- Sources/StreamVideo/Models/ScreenSharingSession.swift
- Sources/StreamVideoSwiftUI/CallView/CallTopView.swift
- Sources/StreamVideoSwiftUI/CallView/CallView.swift
- Sources/StreamVideoSwiftUI/CallView/ScreenSharing/ScreenSharingView.swift
- Sources/StreamVideoSwiftUI/CallViewModel.swift
- Sources/StreamVideoSwiftUI/ViewFactory.swift
- StreamVideo.xcodeproj/project.pbxproj
- StreamVideoSwiftUITests/CallViewModel_Tests.swift
- StreamVideoTests/IntegrationTests/IntegrationTest.swift
- StreamVideoTests/TestUtils/AssertDelay.swift
- docusaurus-old/docs/iOS/advanced/screensharing.md
- docusaurus-old/docs/iOS/client/call-viewmodel.md
- docusaurus/docs/iOS/03-guides/01-client-auth.mdx
- docusaurus/docs/iOS/03-guides/02-joining-creating-calls.mdx
- docusaurus/docs/iOS/03-guides/03-call-and-participant-state.mdx
- docusaurus/docs/iOS/04-ui-components/07-call/07-screen-share-content.mdx
> Update Call state and docs

- Sources/StreamVideoSwiftUI/CallView/CallView.swift
> Fix topView mispositioning

- DemoApp/HTTPClient.swift
- DemoApp/StreamVideoSwiftUIApp+Sentry.swift
- Sources/StreamVideo/HTTPClient/HTTPClient.swift
- Sources/StreamVideo/HTTPClient/InternetConnection.swift
- Sources/StreamVideo/OpenApi/URLSessionTransport.swift
- Sources/StreamVideo/Utils/Logger/Logger.swift
- Sources/StreamVideo/WebRTC/PeerConnection.swift
- Sources/StreamVideo/WebRTC/WebRTCClient.swift
- Sources/StreamVideo/WebSockets/Client/APIKey.swift
- Sources/StreamVideo/WebSockets/Client/URLSessionWebSocketEngine.swift
- Sources/StreamVideo/WebSockets/Client/WebSocketClient.swift
- Sources/StreamVideo/WebSockets/Client/WebSocketPingController.swift
> Add some logging calls and mark subsystems more closely.

- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/StreamVideo.swift
- Sources/StreamVideo/WebRTC/PeerConnection.swift
- Sources/StreamVideo/WebRTC/WebRTCClient.swift
- StreamVideoTests/Controllers/CallController_Tests.swift
- StreamVideoTests/Mock/CallController_Mock.swift
- StreamVideoTests/WebRTC/WebRTCClient_Tests.swift
> Reconnection updates

- DemoApp/CallKitService.swift
- DemoApp/HTTPClient.swift
- DemoApp/LocalStorage.swift
- DemoApp/StreamVideoSwiftUIApp+Sentry.swift
- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/Controllers/CallsController.swift
- Sources/StreamVideo/HTTPClient/HTTPClient.swift
- Sources/StreamVideo/OpenApi/URLSessionTransport.swift
- Sources/StreamVideo/StreamVideo.swift
- Sources/StreamVideo/Utils/Logger/Destination/LogDestination.swift
- Sources/StreamVideo/Utils/Logger/Logger.swift
- Sources/StreamVideo/WebRTC/AudioSession.swift
- Sources/StreamVideo/WebRTC/PeerConnection.swift
- Sources/StreamVideo/WebRTC/SfuMiddleware.swift
- Sources/StreamVideo/WebRTC/VideoCapturer.swift
- Sources/StreamVideo/WebRTC/WebRTCClient.swift
- Sources/StreamVideo/WebSockets/Client/URLSessionWebSocketEngine.swift
- Sources/StreamVideo/WebSockets/Client/WebSocketClient.swift
- Sources/StreamVideoSwiftUI/CallView/Participants/InviteParticipantsViewModel.swift
- Sources/StreamVideoSwiftUI/CallViewModel.swift
- Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift
- Sources/StreamVideoSwiftUI/Utils/CallSoundsPlayer.swift
> Log details more sentry specific

- docusaurus/docs/iOS/03-guides/04-camera-and-microphone.mdx
- docusaurus/docs/iOS/03-guides/06-querying-calls.mdx
- docusaurus/docs/iOS/03-guides/08-permissions-and-moderation.mdx
- docusaurus/docs/iOS/03-guides/09-reactions-and-custom-events.mdx
> Address notion feedback

- Sources/StreamVideo/Call.swift
- Sources/StreamVideo/CallState.swift
- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/Controllers/CallsController.swift
- Sources/StreamVideo/StreamVideo.swift
> Update members when joining a call

- DemoApp/StreamVideoSwiftUIApp+Sentry.swift
- Sources/StreamVideo/HTTPClient/HTTPClient.swift
> Add improved error logging for logging to Sentry.

- Sources/StreamVideo/CallState.swift
- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideoSwiftUI/CallViewModel.swift
- StreamVideoTests/Mock/CallController_Mock.swift
> Exposed participants as array

- docusaurus/docs/iOS/02-tutorials/02-audio-room.mdx
> [Docs]Update AudioRooms tutorial with microphone handling

- docusaurus/docs/iOS/05-ui-cookbook/09-audio-volume-indicator.mdx
> [Docs] Update audio volume indicator

- Sources/StreamVideoSwiftUI/ViewFactory.swift
> [Fix] Modifier declaration

- Sources/StreamVideo/Errors/Errors.swift
- Sources/StreamVideo/WebSockets/Client/WebSocketClient.swift
- Sources/StreamVideo/protobuf/sfu/signal_rpc/signal.twirp.swift
> Improvements in the error handling

- README.md
> Update README.md with Cover image

- .spi.yml
> Add SPI config

- CallIntent/Info.plist
- Sources/StreamVideo/OpenApi/AuthMiddlewares.swift
- Sources/StreamVideo/OpenApi/URLSessionTransport.swift
- Sources/StreamVideo/Utils/EndpointConfig.swift
- Sources/StreamVideo/Utils/SystemEnvironment+XStreamClient.swift
- StreamVideo.xcodeproj/project.pbxproj
> Send SDK version info in all requests

- .github/workflows/docusaurus.yml
> Fix: change branch of docusaurus deploy action to main

- .github/workflows/docusaurus.yml
> Add correct settings to push action

- Sources/StreamVideo/CallState.swift
- Sources/StreamVideo/OpenApi/generated/Models/CallSessionParticipantJoinedEvent.swift
- Sources/StreamVideo/OpenApi/generated/Models/CallSessionParticipantLeftEvent.swift
- Sources/StreamVideoSwiftUI/CallingViews/PreJoiningViewModel.swift
- Sources/StreamVideoSwiftUI/Models/CallEventsHandler.swift
- StreamVideoSwiftUITests/CallViewModel_Tests.swift
- StreamVideoSwiftUITests/Utils/CallEventsHandler_Tests.swift
> Updated session participant events

- Sources/StreamVideo/StreamVideo.swift
- StreamVideoTests/IntegrationTests/CallCRUDTests.swift
- StreamVideoTests/IntegrationTests/IntegrationTest.swift
Resolve https://github.com/GetStream/ios-issues-tracking/issues/488
> StreamVideo API tests

- Sources/StreamVideoSwiftUI/CallView/CallView.swift
- SwiftUIDemoAppUITests/Robots/UserRobot.swift
- SwiftUIDemoAppUITests/Tests/CallViewsTests.swift
- SwiftUIDemoAppUITests/Tests/ParticipantActionsTests.swift
> [Fix]Move 'Participant joined popup' to the top of the call screen

- docusaurus/docs/iOS/02-tutorials/01-video-calling.mdx
> [Docs]Update video tutorial to use VideoCallParticipantView

- Sources/StreamVideo/CallState.swift
- Sources/StreamVideo/Models/CoordinatorModels.swift
- docusaurus/docs/iOS/02-tutorials/03-livestream.mdx
Easier access to the rtmp address and streaming key.
> Updated the ingress property

- Sources/StreamVideo/Call.swift
- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/Models/VideoOptions.swift
- Sources/StreamVideo/StreamVideo.swift
- Sources/StreamVideo/WebRTC/Screensharing/ScreenshareCapturer.swift
- Sources/StreamVideo/WebRTC/VideoCapturer.swift
- Sources/StreamVideo/WebRTC/VideoCapturing.swift
- Sources/StreamVideo/WebRTC/VideoCapturingUtils.swift
- Sources/StreamVideoSwiftUI/CallViewModel.swift
- StreamVideo.xcodeproj/project.pbxproj
- StreamVideoTests/Call/Call_Tests.swift
- StreamVideoTests/Controllers/CallController_Tests.swift
- StreamVideoTests/Mock/CallController_Mock.swift
- StreamVideoTests/StreamVideo.xctestplan
- StreamVideoTests/WebRTC/VideoCapturerUtils_Tests.swift
Try to use the target resolution provided by the backend.
> Target resolution read from backend

- CHANGELOG.md
- Sources/StreamVideoSwiftUI/CallContainer.swift
- Sources/StreamVideoSwiftUI/CallView/CallView.swift
- Sources/StreamVideoSwiftUI/CallView/MinimizedCallView.swift
- Sources/StreamVideoSwiftUI/CallView/ParticipantsFullScreenLayout.swift
- Sources/StreamVideoSwiftUI/CallView/ParticipantsGridLayout.swift
- Sources/StreamVideoSwiftUI/CallView/ParticipantsGridView.swift
- Sources/StreamVideoSwiftUI/CallView/ParticipantsSpotlightLayout.swift
- Sources/StreamVideoSwiftUI/CallView/ScreenSharing/ScreenSharingView.swift
- Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
- Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
- Sources/StreamVideoSwiftUI/ViewFactory.swift
- StreamVideoSwiftUITests/CallView/ParticipantsFullScreenLayout_Tests.swift
- StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift
- StreamVideoSwiftUITests/CallView/ParticipantsSpotlightLayout_Tests.swift
- TestTools/TestData/ViewFactory.swift
- docusaurus/docs/iOS/02-tutorials/01-video-calling.mdx
- docusaurus/docs/iOS/03-guides/10-view-slots.mdx
- docusaurus/docs/iOS/04-ui-components/02-video-renderer.mdx
- docusaurus/docs/iOS/04-ui-components/07-call/04-active-call.mdx
- docusaurus/docs/iOS/04-ui-components/08-participants/01-call-participant.mdx
- docusaurus/docs/iOS/05-ui-cookbook/04-video-layout.mdx
- docusaurus/docs/iOS/05-ui-cookbook/07-video-fallback.mdx
The call view is provided to the participant view, would be needed for the PiP implementation (views will feed the call with the video data for PiP).
> Refactoring participant view

- DemoApp/Sources/Components/MemoryLogDestination/MemoryLogViewer.swift
- DemoApp/Sources/Views/CallModifier/DemoCallModifier.swift
- DemoApp/Sources/Views/CallView/DemoCallView.swift
- DemoApp/Sources/Views/ThermalStateViewModifier/ThermalStateViewModifier.swift
- Sources/StreamVideo/Utils/ThermalStateObserver.swift
- Sources/StreamVideo/WebRTC/PeerConnection.swift
- Sources/StreamVideo/WebRTC/StreamVideoCaptureHandler.swift
- Sources/StreamVideo/WebRTC/WebRTCClient.swift
- Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
- Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift
- StreamVideo.xcodeproj/project.pbxproj
> Thermal and performance improvements

- Sources/StreamVideo/WebRTC/PeerConnection.swift
> Revert unnecessary change

- DemoApp/Sources/Components/Reactions/ReactionsHelper.swift
- DemoApp/Sources/Views/VideoCallParticipantModifier/DemoVideoCallParticipantModifier.swift
> Fix reactions not showing for remote participants

- DemoApp/Sources/Views/WaitingLocalUserView/DemoWaitingLocalUserView.swift
- Join a call where you will be the only participant
- The view to share the call's link should be visible
- Open the chat and close it
- The view should be hidden and then become visible again
> Fix waiting user view appearance

- StreamVideo.xcodeproj/project.pbxproj
> Fix compilation error on DemoUIKit

- DemoApp/Info.plist
> Fix Google URL scheme issues

- DemoApp/Info.plist
- DemoApp/Sources/Components/AppEnvironment.swift
- DemoApp/Sources/Views/Login/GoogleHelper.swift
- DemoApp/Sources/Views/Login/LoginView.swift
- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
> Update release flow

- DemoApp/Sources/Components/Stats/RawStatsView.swift
- DemoApp/Sources/Views/CallView/DemoCallsView.swift
- Sources/StreamVideoSwiftUI/CallView/Participants/InviteParticipantsView.swift
> Fix compilation errors on iOS 14

- SwiftUIDemoAppUITests/Pages/CallPage.swift
Relates to https://github.com/GetStream/stream-video-swift/pull/210
> Update e2e locators

- DemoApp/Sources/Components/DemoAppViewFactory.swift
- DemoApp/Sources/Views/CallView/DemoCallView.swift
- DemoApp/Sources/Views/CustomCallView.swift
- Sources/StreamVideoSwiftUI/CallView/LocalParticipantViewModifier.swift
- Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift
- Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift
- Sources/StreamVideoSwiftUI/CallingViews/iOS13/PreJoiningView_iOS13.swift
- StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
Reverts GetStream/stream-video-swift#175
> Revert "Use single instance for the microphoneChecker"

- Sources/StreamVideo/WebRTC/WebRTCClient.swift
> Remove unused code

- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/WebRTC/PeerConnection.swift
- Sources/StreamVideo/WebRTC/PeerConnectionFactory.swift
- Sources/StreamVideo/WebRTC/WebRTCClient.swift
- Sources/StreamVideo/WebSockets/Client/WebSocketClient.swift
- Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
+ Cleaning up unnecessary code from PeerConnection
+ Passing the transceive mid when it's avaiblable for video and screensharing tracks
> [Fix]Session Migration

- DemoApp/Sources/AppDelegate.swift
- Sources/StreamVideo/Models/CallSettings.swift
- Sources/StreamVideo/WebRTC/SimulatorScreenCapturer.swift
- Sources/StreamVideo/WebRTC/VideoCapturer.swift
- StreamVideo.xcodeproj/project.pbxproj
Allow debugging video streaming from the simulator.
> [Enhancement]Allow video debugging from the simulator

- DemoApp/Sources/Views/Login/GoogleHelper.swift
- DemoApp/Sources/Views/Login/LoginView.swift
- DemoApp/Sources/Views/Login/LoginViewModel.swift
> [Fix]Broken Google SignIn on DemoApp

- docusaurus/docs/iOS/03-guides/15-migration-from-dolby.mdx
|  Part 1  | Part 2 |
| -------- | -------|
| ![part1](https://github.com/GetStream/stream-video-swift/assets/472467/910de04a-636e-468a-b95a-a6332acaeb40) | ![part2](https://github.com/GetStream/stream-video-swift/assets/472467/045bc6f0-9955-4959-b7d6-03eafa54ea37)|
_Provide a funny gif or image that relates to your work on this …
> [Docs]Dolby to Stream AudioRoom migration

- Sources/StreamVideo/WebRTC/SfuMiddleware.swift
> Remove track removal code

- DemoApp/Sources/Views/Controls/DemoControls.swift
In simulator hide the broadcast button.
> Disable broadcast button on simulators

- DemoApp/Sources/Components/Router.swift
> Fixed a warning in the demo app

- Sources/StreamVideo/Utils/SystemEnvironment+XStreamClient.swift
- Sources/StreamVideo/WebRTC/WebRTCClient.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/710
Add clientDetails on joinRequest
> Add clientDetails on JoinRequest

- Sources/StreamVideoSwiftUI/CallView/Participants/CallParticipantsInfoView.swift
- Sources/StreamVideoSwiftUI/CallView/ParticipantsGridLayout.swift
- Sources/StreamVideoSwiftUI/Utils/HalfSheetView.swift
- Sources/StreamVideoSwiftUI/Utils/Modifiers.swift
A small PR to address some feedback from UI/UX and reduce the size and noise on the subsequent PRs.
> [Redesign]Address UI/UX feedback

- DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
- DemoApp/Sources/DemoApp.swift
- DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
- DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
- DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
- DemoApp/Sources/Views/CallView/DemoCallContentView.swift
- DemoApp/Sources/Views/CallView/DemoCallingTopView.swift
- DemoApp/Sources/Views/Login/LoginView.swift
- DemoApp/Sources/Views/Login/LoginViewModel.swift
- StreamVideo.xcodeproj/project.pbxproj
- SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift
- fastlane/sinatra.rb
Resolves https://github.com/GetStream/ios-issues-tracking/issues/721
Improve user handling and logging in for the DemoApp, with the purpose to make testing easier and more stable.
> [Fix]User handling in demo app

- Sources/StreamVideo/Call.swift
- Sources/StreamVideo/StreamVideo.swift
- Sources/StreamVideo/Utils/Utils.swift
Complete event stream continuations to ensure correct lifecycle for event streaming listeners.
> [Fix]Finish stream continuations

- DemoApp/Sources/Components/DemoAppViewFactory.swift
- DemoApp/Sources/Extensions/CallViewModel+Snapshot.swift
- DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift
- DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
- DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
- DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/16-snapshot.swift
- Sources/StreamVideoSwiftUI/CallView/ViewModifiers/Snapshot/SnapshotViewModifier.swift
- StreamVideoSwiftUITests/StreamVideoSwiftUI.xctestplan
- StreamVideoTests/TestUtils/AssertDelay.swift
- docusaurus/docs/iOS/05-ui-cookbook/16-snapshot.mdx
Fix some small issues when using the snapshot modifier and updating the relevant docs.
> Fix small snapshot issues

- Sources/StreamVideo/CallSettings/CameraManager.swift
- Sources/StreamVideo/CallSettings/MicrophoneManager.swift
- Sources/StreamVideo/CallSettings/SpeakerManager.swift
- Sources/StreamVideo/CallState.swift
- Sources/StreamVideo/StreamVideo.swift
- Sources/StreamVideo/WebRTC/Screensharing/BroadcastObserver.swift
- Sources/StreamVideoSwiftUI/CallView/CallDurationView.swift
> Fix warnings on older Xcode versions

- Sources/StreamVideo/StreamVideo.swift
> Minor text changes

- README.md
Tutorials need to be linked from the readme.
> Updated the README with tutorial links

- .github/workflows/testflight.yml
- StreamVideo.xcodeproj/project.pbxproj
- fastlane/Fastfile
> [CI/CD]Update testflight lane

- SwiftUIDemoAppUITests/Tests/DeeplinkTests.swift
> [Fix]Universal link tests

- CHANGELOG.md
- Sources/StreamVideo/Generated/SystemEnvironment+Version.swift
- Sources/StreamVideo/Info.plist
- Sources/StreamVideoSwiftUI/Info.plist
- Sources/StreamVideoUIKit/Info.plist
- StreamVideo-XCFramework.podspec
- StreamVideo.podspec
- StreamVideoArtifacts.json
- StreamVideoSwiftUI-XCFramework.podspec
- StreamVideoSwiftUI.podspec
- StreamVideoUIKit-XCFramework.podspec
- StreamVideoUIKit.podspec
- New API that allows adding/removing capturePhotoOutput, videoOutput on the local participant's AVCaptureSession. [#301](https://github.com/GetStream/stream-video-swift/pull/301)
- New API that allows zooming the local participant's camera. [#301](https://github.com/GetStream/stream-video-swift/pull/301)
- VideoFilters for blurring or setting an image as background. [#309](https://github.com/GetStream/stream-video-swift/pull/309)
- Updated Web Socket reconnection logic. [#314](https://github.com/GetStream/stream-video-swift/pull/314)
> 0.5.1 Release

- Sources/StreamVideo/WebRTC/StreamVideoCaptureHandler.swift
- Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/758
> [Fix]Local video rotate on YAxis when turning off video

- Sources/StreamVideo/WebRTC/Statistics/Statistics+Convenience.swift
- Sources/StreamVideo/WebRTC/WebRTCClient.swift
- StreamVideo.xcodeproj/project.pbxproj
- StreamVideoTests/WebRTC/Statistics/CallStatsReporting_Tests.swift
- StreamVideoTests/WebRTC/Statistics/Mocks/MockStreamStatistics.swift
- StreamVideoTests/WebRTC/Statistics/StreamCallStatisticsFormatter_Tests.swift
Fixes so the backend can parse the stats correctly.
> Updated the stats report format

- Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
- Sources/StreamVideoSwiftUI/CallView/VideoRenderer.swift
> Rotate local user feed on all layouts

- Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
> [Fix]Local user mirroring

- Sources/StreamVideoUIKit/CallViewController.swift
> [UIKit]Fix view positioning

- docusaurus/docs/iOS/06-advanced/04-troubleshooting-calls.mdx
Troubleshooting the most common call issues.
> Added troubleshooting guide

- Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureController.swift
Stop Picture-in-Picture whenever the app moves to foreground.
This behaviour is easily noticeable if you follow the steps in the manual testing notes.
In UIKit applications, we observe the application state. Whenever the state changes to foreground, if Picture-in-Picture is active, we stop it.
- Join a call from a high end device(newer iPads and iPhones)
- Move the call to the background and wait for PiP presentation
- Once you have the PiP move back to the app (foreground)
> [Fix]Stop PiP when app moves to foreground

- docusaurus/docs/iOS/06-advanced/10-background-modes.mdx
> docs: fix staging link in background modes

- docusaurus/docs/iOS/04-ui-components/02-video-renderer.mdx
> Added docs for mirroring the video renderer view

- Sources/StreamVideo/protobuf/ProtoModel.swift
- Sources/StreamVideo/protobuf/sfu/signal_rpc/signal.pb.swift
- Sources/StreamVideo/protobuf/sfu/signal_rpc/signal.twirp.swift
Generated code needed for handling noise cancellation. More details here: https://www.notion.so/stream-wiki/Noise-Cancellation-c839aed9dcc5402684264e9e824c4212
These methods should be called when noise cancellation is started and stopped (out of scope for this PR).
Just generated code.
> Added protobufs models and methods for noise cancellation

- docusaurus/docs/iOS/03-guides/03-call-and-participant-state.mdx
- docusaurus/docs/iOS/06-advanced/07-gdpr-endpoints.mdx
> Docs updates

- Sources/StreamVideo/WebRTC/SfuMiddleware.swift
- Sources/StreamVideo/protobuf/ProtoModel.swift
- Sources/StreamVideo/protobuf/sfu/event/events.pb.swift
- Sources/StreamVideo/protobuf/sfu/models/models.pb.swift
- Sources/StreamVideo/protobuf/sfu/signal_rpc/signal.pb.swift
> Generated latest protobuf code with ended event

- docusaurus/docs/iOS/05-ui-cookbook/18-transcriptions.mdx
- docusaurus/docs/iOS/06-advanced/03-callkit-integration.mdx
> [Docs]Small corrections/updates

- CHANGELOG.md
- DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
- DemoApp/Sources/Views/CallView/DemoCallContainerView.swift
- DemoApp/Sources/Views/CallView/DemoCallsViewModel.swift
- DemoAppUIKit/Sources/HomeViewController.swift
- DocumentationTests/DocumentationTests/DocumentationTests/03-guides/14-swiftui-vs-uikit.swift
- DocumentationTests/DocumentationTests/DocumentationTests/04-ui-components/05-uikit-customizations.swift
- DocumentationTests/DocumentationTests/DocumentationTests/04-ui-components/06-view-model.swift
- DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
- Sources/StreamVideo/Models/Member.swift
- Sources/StreamVideoSwiftUI/CallViewModel.swift
- Sources/StreamVideoSwiftUI/ViewFactory.swift
- Sources/StreamVideoUIKit/CallViewController.swift
- StreamVideoSwiftUITests/CallViewModel_Tests.swift
- StreamVideoSwiftUITests/CallingViews/OutgoingCallView_Tests.swift
- StreamVideoUIKitTests/CallViewController_Tests.swift
- SwiftUIDemoAppUITests/Pages/CallPage.swift
- SwiftUIDemoAppUITests/Robots/UserRobot+Asserts.swift
- docusaurus/docs/iOS/04-ui-components/06-view-model.mdx
Use `Member` instead of `MemberRequest` in the public call view model methods.
> Fix a bug with outgoing call showing ids

- fastlane/Fastfile
- https://github.com/GetStream/stream-video-swift/actions/runs/8832223471
- https://github.com/GetStream/stream-video-swift/actions/runs/8846718662
> Remove auto-signing for Debug builds on CI

- DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
- DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
- DocumentationTests/DocumentationTests/DocumentationTests/03-guides/16-noise-cancellation.swift
- DocumentationTests/DocumentationTests/DocumentationTests/05-ui-cookbook/19-noise-cancellation.swift
- DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/06-apply-video-filters.swift
- DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
- StreamVideo.xcodeproj/project.pbxproj
- docusaurus/docs/iOS/03-guides/04-camera-and-microphone.mdx
- docusaurus/docs/iOS/03-guides/04-noise-cancellation.mdx
- docusaurus/docs/iOS/03-guides/16-noise-cancellation.mdx
- docusaurus/docs/iOS/05-ui-cookbook/19-noise-cancellation.mdx
- docusaurus/docs/iOS/06-advanced/06-apply-video-filters.mdx
Provide integration steps for `StreamNoiseCancellation` SDK.
> Update API and docs for NoiseCancellation

- Sources/StreamVideoSwiftUI/CallingViews/IncomingCallView.swift
- Sources/StreamVideoSwiftUI/Models/CallEventsHandler.swift
> Fixed a bug with incoming call view

- README.md
> [Docs]Update Readme with NoiseCancellation

- docusaurus/docs/iOS/03-guides/04-noise-cancellation.mdx
- docusaurus/docs/iOS/05-ui-cookbook/19-noise-cancellation.mdx
> [Docs]NoiseCancellation docs to mention performance needs

- Sources/StreamVideo/Models/CallParticipant.swift
- docusaurus/docs/iOS/03-guides/03-call-and-participant-state.mdx
> Introduced User object in CallParticipant

- Sources/StreamVideo/WebRTC/SfuMiddleware.swift
- Sources/StreamVideo/protobuf/sfu/event/events.pb.swift
- Sources/StreamVideo/protobuf/sfu/models/models.pb.swift
- StreamVideoTests/WebRTC/WebRTCClient_Tests.swift
Resolves https://github.com/GetStream/ios-issues-tracking/issues/817.
Handle the new participant updated SFU event.
> Handle SFU participant updated event

- Sources/StreamVideo/CallKit/CallKitService.swift
> [Fix]CallKitService ending call while busy

- CHANGELOG.md
- Sources/StreamVideo/Models/User.swift
- Sources/StreamVideo/StreamVideo.swift
> [Fix]Undo name override on User

- Sources/StreamVideo/WebRTC/SimulatorScreenCapturer.swift
- Sources/StreamVideo/WebRTC/VideoCapturer.swift
- Sources/StreamVideo/WebRTC/WebRTCClient.swift
> [Fix]Memory issue on SimulatorScreenCapturer

- Package.swift
> Remove macOS from Package.swift

- Sources/StreamVideoSwiftUI/CallContainer.swift
- Sources/StreamVideoSwiftUI/CallingViews/iOS13/VideoView_iOS13.swift
- Sources/StreamVideoSwiftUI/ViewFactory.swift
> Exposed method for customizing the minimized call view

- Sources/StreamVideo/VideoConfig.swift
- Sources/StreamVideo/WebRTC/AudioFilter/StreamAudioProcessingModule.swift
In the DemoApp, try the logout/login flow a few times. In between logouts make sure to join calls and verify things work as expected.
> [Fix]StreamAudioFilterProcessingModule release issues

- CHANGELOG.md
- Sources/StreamVideo/CallKit/CallKitService.swift
- StreamVideo.xcodeproj/project.pbxproj
- StreamVideoTests/CallKit/CallKitServiceTests.swift
- StreamVideoTests/Mock/MockCXCallController.swift
- StreamVideoTests/StreamVideo.xctestplan
- StreamVideoTests/Utilities/Dummy/GetCallResponse+Dummy.swift
- StreamVideoTests/Utilities/Mocks/MockCXProvider.swift
> Enhancement/allow  callkit service to manage multiple calls

- DemoApp/Sources/Components/Feedback/DemoFeedbackView.swift
> [Minor]Preselect 5 star rating

- DemoApp/Sources/Components/AppEnvironment.swift
- DemoApp/Sources/Components/SessionTimer/SessionTimer.swift
- DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
- DemoApp/Sources/Views/CallView/DemoCallView.swift
- DemoApp/Sources/Views/CallView/DemoSessionTimerView.swift
- DemoApp/Sources/Views/Login/DebugMenu.swift
- Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift
- Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
- Sources/StreamVideoSwiftUI/CallViewModel.swift
- StreamVideo.xcodeproj/project.pbxproj
- docusaurus/docs/iOS/05-ui-cookbook/21-session-timers.mdx
- docusaurus/shared
Resolves https://github.com/GetStream/ios-issues-tracking/issues/749.
Show an example on how to use session timers.
For now available on ProntoStaging (available from the debug menu). Set a call duration of 2 minutes (also in the menu), and wait for a minute.
> Cookbook for session timers

- Sources/StreamVideo/OpenApi/URLSessionTransport.swift
- Sources/StreamVideo/Utils/UUIDProviding/StreamUUIDFactory.swift
- Sources/StreamVideo/WebRTC/WebRTCClient.swift
- Sources/StreamVideo/WebSockets/Client/WebSocketClient.swift
- Sources/StreamVideo/WebSockets/Events/Event.swift
- Sources/StreamVideo/WebSockets/Events/EventNotificationCenter.swift
Add comments, resolve warnings and improve logging.
> [Enhancement]Minor improvements

- DemoApp/Sources/Components/AppEnvironment.swift
- DemoApp/Sources/Components/AppState.swift
- DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
- DemoApp/Sources/Components/Router.swift
- DemoApp/Sources/Components/Storage/UnsecureRepository.swift
- DemoApp/Sources/Extensions/User+Demo.swift
- DemoApp/Sources/Extensions/View+AlertWithTextField.swift
- DemoApp/Sources/Views/Login/AddUserView.swift
- DemoApp/Sources/Views/Login/DebugMenu.swift
- DemoApp/Sources/Views/Login/LoginView.swift
- DemoApp/Sources/Views/Login/LoginViewModel.swift
- Sources/StreamVideo/Models/PushNotificationsConfig.swift
- StreamVideo.xcodeproj/project.pbxproj
Fix the Add User flow used in debugging. Adding a way to provide a custom ApiKey and Token.
> [Debug] Fix add new user and customise the environment

- Sources/StreamVideo/CallKit/CallKitService.swift
> [Fix]Cancel ringing timer when call is answered elsewhere

- DemoApp/Sources/Components/AppEnvironment.swift
- DemoApp/Sources/Views/WaitingLocalUserView/DemoWaitingLocalUserView.swift
- StreamVideo.xcodeproj/project.pbxproj
Provide correctly formatted shareable links for all environments.
For every environment join a call and share the link to another device. The other device should join successfully on the new call.
> [Fix]Demo share link format

- Sources/StreamVideo/StreamVideo.swift
- Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapter.swift
- StreamVideoSwiftUITests/CallViewModel_Tests.swift
- StreamVideoSwiftUITests/Utils/PictureInPicture/StreamPictureInPictureTrackStateAdapterTests.swift
- StreamVideoTests/StreamVideoTestCase.swift
- StreamVideoTests/Utilities/Extensions/XCTestCase+PredicateFulfillment.swift
> [Fix]Flakey tests

- .github/workflows/cron-checks.yml
- .github/workflows/smoke-checks.yml
- Scripts/bootstrap.sh
- fastlane/Fastfile
Relates to:
- https://github.com/GetStream/stream-chat-swiftui/pull/521
- https://github.com/GetStream/stream-chat-swift/pull/3259
> [CI] Make CI great again

- DemoApp/Sources/Components/MemoryLogDestination/OSLogDestination.swift
- DemoApp/Sources/Components/Snapshot/LocalParticipantSnapshotViewModel.swift
- DemoApp/Sources/Extensions/DemoApp+Sentry.swift
- Sources/StreamVideo/Utils/AudioRecorder/StreamCallAudioRecorder.swift
- Sources/StreamVideo/Utils/Logger/Destination/LogDestination.swift
- Sources/StreamVideo/Utils/Logger/Logger.swift
- Sources/StreamVideo/WebRTC/PeerConnection.swift
- Sources/StreamVideo/WebRTC/SfuMiddleware.swift
- Sources/StreamVideo/WebRTC/VideoCapturingUtils.swift
- Sources/StreamVideoSwiftUI/CallView/ViewModifiers/CallEndedViewModifier.swift
Provide a clearer console is vital for developing and debugging. This revision is turning more into OSLog while tries to improve logging on core areas of the SDK.
By setting this filter `Category: Video` on Xcode's console all irrelevant logs are being removed.
> [Logs]Improving logs

- Sources/StreamVideo/WebRTC/WebRTCClient.swift
> [Fix]Project warnings

- StreamVideo.xcodeproj/project.pbxproj
Fixes the build errors in Xcode 16 beta.
> Updated the Sentry version in the demo app

- .github/workflows/smoke-checks.yml
> [CI] Lint pod on release and nighty only

- Sources/StreamVideo/WebRTC/SfuMiddleware.swift
- Sources/StreamVideo/WebSockets/Events/Event.swift
- Sources/StreamVideo/protobuf/sfu/event/events.pb.swift
- Sources/StreamVideo/protobuf/sfu/models/models.pb.swift
Will help with https://stream-io.atlassian.net/browse/PBE-5200.
Generated code for the v2 reconnection flow.
> Generated code for the new reconnection mechanism

- .github/workflows/sdk-size-metrics.yml
- .github/workflows/smoke-checks.yml
- .gitignore
- fastlane/Fastfile
- fastlane/sdk_size_export_options.plist
Resolve https://stream-io.atlassian.net/browse/PBE-5302
Comment SDK size on every commit
> [CI] Comment SDK size on every commit

- README.md
- fastlane/Fastfile
Resolve https://stream-io.atlassian.net/browse/PBE-5350
Automatically update SDK size badges in README.md
> [CI] Automatically update SDK size badges in README.md

- docusaurus/docs/iOS/06-advanced/02-push-notifications.mdx
> Update the notification docs

- Sources/StreamVideo/CallState.swift
> [Fix]Recording state when failed

- .github/workflows/cron-checks.yml
- .github/workflows/publish-release.yml
- .github/workflows/sdk-size-metrics.yml
- .github/workflows/smoke-checks.yml
- .github/workflows/start-new-release.yml
- .github/workflows/testflight.yml
- fastlane/Allurefile
- fastlane/Fastfile
Similar to https://github.com/GetStream/stream-chat-swift/pull/3349
> [CI] Correctly retrieve a git branch on CI

- .github/workflows/release-merge.yml
- .github/workflows/release-publish.yml
- .github/workflows/release-start.yml
- fastlane/Fastfile
Resolve https://stream-io.atlassian.net/browse/PBE-5401
Automate the merge of the release branches
> [CI] Automate the merge of the release branches

- .github/workflows/cron-checks.yml
- .gitignore
- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
Copy-pasting https://github.com/GetStream/stream-chat-swift/pull/3371
> [CI] Share fastlane lanes across platforms

- Sources/StreamVideo/protobuf/sfu/models/models.pb.swift
> Added muted property to announced tracks data

- .github/workflows/release-publish.yml
- fastlane/Fastfile
- Do not depend on release PR to publish the release
> [CI] Update publish release flow

- Sources/StreamVideo/Controllers/CallController.swift
Provide a workaround for the backend issue related to the ParticipantCountUpdated event.
> [Workaround]ParticipantCount event backend fix

- Sources/StreamVideo/Models/CallParticipant.swift
- Sources/StreamVideo/Models/ConnectionQuality.swift
- Sources/StreamVideo/Models/User.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
- Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
- Sources/StreamVideoSwiftUI/CallView/VisibilityThresholdModifier.swift
> [Fix]Missing tracks

- Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
Resolves https://stream-io.atlassian.net/browse/PBE-5989
> Retain camera position after reconnection

- Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Migrated.swift
- StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_MigratedStageTests.swift
> [Fix]Migration not working due to event not being received

- CHANGELOG.md
- Sources/StreamVideoSwiftUI/CallViewModel.swift
Resolves https://stream-io.atlassian.net/browse/PBE-6055
Allow passing customData when starting/joining calls through CallViewModel.
> [Enhancement]Allow CustomData passing to CallViewModel

- SwiftUIDemoAppUITests/Tests/ReconnectionTests.swift
> Reenable test reconnecting message

- StreamVideoTests/Mock/MockRTCPeerConnection.swift
- StreamVideoTests/WebRTC/SFU/SFUEventAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/Adapters/ICEAdapter_Tests.swift
> Add more tests for ICEAdapter

- Sources/StreamVideo/Call.swift
- Sources/StreamVideo/Controllers/CallController.swift
- StreamVideoTests/IntegrationTests/CallCRUDTests.swift
- StreamVideoTests/IntegrationTests/IntegrationTest.swift
> Reenable crud tests

- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/Models/CallParticipant.swift
- Sources/StreamVideo/WebRTC/v2/Extensions/Foundation/Publisher+TaskSink.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/Adapters/ICEAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/Protocols/StreamRTCPeerConnectionProtocol.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCTemporaryPeerConnection.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/StreamRTCPeerConnection.swift
- Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
- Sources/StreamVideoSwiftUI/CallView/VideoRenderer/VideoRendererView.swift
- StreamVideoTests/Mock/MockRTCPeerConnectionCoordinator.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
> [Fix]UI freeze

- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/Models/CallParticipant.swift
- Sources/StreamVideo/WebRTC/v2/Extensions/Foundation/Publisher+TaskSink.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/Adapters/ICEAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/Protocols/StreamRTCPeerConnectionProtocol.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCTemporaryPeerConnection.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/StreamRTCPeerConnection.swift
- Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
- Sources/StreamVideoSwiftUI/CallView/VideoRenderer/VideoRendererView.swift
- StreamVideoTests/Mock/MockRTCPeerConnectionCoordinator.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
> [Fix]Revert reconnection ui-freeze

- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/Models/CallParticipant.swift
- Sources/StreamVideo/WebRTC/v2/Extensions/Foundation/Publisher+TaskSink.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/Adapters/ICEAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/Protocols/StreamRTCPeerConnectionProtocol.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCTemporaryPeerConnection.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/StreamRTCPeerConnection.swift
- Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
- Sources/StreamVideoSwiftUI/CallView/VideoRenderer/VideoRendererView.swift
- StreamVideoTests/Mock/MockRTCPeerConnectionCoordinator.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
> [Fix]Revert reconnection ui-freeze (#548)

- Sources/StreamVideo/Utils/LocationFetcher.swift
Align with other SDKs approach on fetching location hint, by retrying a few times if it fails. (https://github.com/GetStream/stream-video-js/pull/1505)
> [Fix]Retry location hint

- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
- From a web participant in pronto
- open the console and trigger multiple rejoins
- Participants should always be correctly updated
> [Fix]Participants duplication

- DemoApp/Sources/Components/Router.swift
- DemoApp/Sources/Views/StatsView/DemoStatsAdapter.swift
- DemoApp/Sources/Views/StatsView/DemoStatsView.swift
- StreamVideo.xcodeproj/project.pbxproj
Improve the Stats screen in the Demo app by:
1. Including statReports received even when the screen wasn't open
2. Improve UI Presentation by fitting to available spac
> [Demo]Improve stats view

- Sources/StreamVideo/Utils/DeviceOrientation/StreamDeviceOrientationAdapter.swift
- Sources/StreamVideo/WebRTC/VideoCapturing/StreamVideoCaptureHandler.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
- StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift
- StreamVideoTests/Controllers/CallController_Tests.swift
- StreamVideoTests/WebRTC/VideoCapturing/StreamVideoCaptureHandler_Tests.swift
- StreamVideoTests/WebRTC/v2/IntegrationTests/WebRTCIntegrationTests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalScreenShareMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/WebRTCStateAdapter_Tests.swift
> [Fix]Failing iOS 15 tests

- CHANGELOG.md
- Sources/StreamVideo/WebSockets/Client/ConnectionRecoveryHandler.swift
> [Fix]StreamVideo unable to connect from CallKit

- README.md
> Updated the roadmap

- CHANGELOG.md
- Sources/StreamVideo/CallKit/CallKitAdapter.swift
- Sources/StreamVideo/CallKit/CallKitService.swift
- StreamVideoTests/CallKit/CallKitServiceTests.swift
Allow custom ringtones for CallKit ringing calls.
> [CallKit]Custom ringtone support

- Sources/StreamVideo/protobuf/sfu/models/models.pb.swift
> Added publish option id to the track info

- Sources/StreamVideo/Call.swift
- Sources/StreamVideo/CallState.swift
- StreamVideoTests/Call/Call_Tests.swift
> Exposed methods for RTMP broadcasting

- .github/workflows/record-snapshots.yml
- .github/workflows/smoke-checks.yml
- fastlane/Fastfile
Avoid re-recording all the snapshots on CI
- [SwiftUI Soft-recording](https://github.com/GetStream/stream-video-swift/actions/runs/13263026065/job/37023745823)
- [SwiftUI Hard-recording](https://github.com/GetStream/stream-video-swift/actions/runs/13263470124/job/37025109480)
- [UIKit Soft-recording](https://github.com/GetStream/stream-video-swift/actions/runs/13265127029/job/37030564961)
- [UIKit Hard-recording](https://github.com/GetStream/stream-video-swift/actions/runs/13265669414/job/37032383881)
> [CI] Snapshots recording improvement

- Sources/StreamVideo/Utils/SystemEnvironment+XStreamClient.swift
Resolves https://linear.app/stream/issue/IOS-705/update-x-stream-client-header.
> X-Stream-Client header update

- .github/workflows/cron-checks.yml
- .github/workflows/smoke-checks.yml
- .github/workflows/testflight.yml
- .github/workflows/update-copyright.yml
https://getstream.slack.com/archives/C08E4DPVA69
> [CI] Route nightly checks fail reports to a dedicated Slack channel

- DemoApp/Sources/Components/DemoAppViewFactory.swift
- Sources/StreamVideo/HTTPClient/HTTPClient.swift
- Sources/StreamVideo/Utils/AudioSession/AudioRecorder/AVAudioRecorderBuilder.swift
- Sources/StreamVideo/Utils/DeviceOrientation/StreamDeviceOrientationAdapter.swift
- Sources/StreamVideo/Utils/Sorting.swift
- Sources/StreamVideo/Utils/Swift6Migration/Sendable+Extensions.swift
- Sources/StreamVideoSwiftUI/CallView/VideoRenderer/VideoRenderer.swift
- Sources/StreamVideoSwiftUI/CallView/VideoRenderer/VideoRendererView.swift
- Sources/StreamVideoSwiftUI/CallView/ViewModifiers/CallEndedViewModifier.swift
- Sources/StreamVideoSwiftUI/CallView/ViewModifiers/ParticipantEventViewModifier.swift
- Sources/StreamVideoSwiftUI/CallingViews/PreJoiningViewModel.swift
- Sources/StreamVideoSwiftUI/CallingViews/iOS13/BackportStateObject.swift
- Sources/StreamVideoSwiftUI/Models/CallEvents.swift
- Sources/StreamVideoSwiftUI/Utils/PictureInPicture/StreamYUVToARGBConversion.swift
- Sources/StreamVideoSwiftUI/Utils/VideoRendererPool/VideoRendererPool.swift
- StreamVideoSwiftUITests/CallView/ParticipantsGridLayout_Tests.swift
- StreamVideoTests/Mock/CallController_Mock.swift
> [Swift6 Migration]Fix Xcode 15 issues

- fastlane/Fastfile
> Improve public interface validation

- DemoApp/Sources/Components/AppEnvironment.swift
- DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
- DemoApp/Sources/Views/Login/DebugMenu.swift
> Add pronto frankfurt C2 test config

- DocumentationTests/DocumentationTests/DocumentationTests/06-advanced/03-callkit-integration.swift
- DocumentationTests/DocumentationTests/DocumentationTests/GloballyUsedVariables.swift
This revision reorders the contents of the callkit-integration documentation tests in order to match the order in the document.
> [Enhancement]Update order for CallKit documentation tests

- DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
- Sources/StreamVideo/Models/CallSettings.swift
- Sources/StreamVideo/Utils/BundleExtensions.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
- Sources/StreamVideoSwiftUI/Utils/Camera.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
> [Enhancement]Camera access request is driven by Plist usage

- .gitignore
- CHANGELOG.md
- DemoApp/Sources/Views/CallView/CallingView/DetailedCallingView.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
- Sources/StreamVideoSwiftUI/Livestreaming/LivestreamPlayer.swift
- StreamVideoTests/Utils/StateMachine/StreamStateMachine_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter_Tests.swift
Avoid calling SetPublisher when no tracks are published.
> [Fix]Unnecessary SetPublisher requests

- CHANGELOG.md
- Sources/StreamVideoSwiftUI/CallingViews/MicrophoneChecker.swift
- StreamVideoSwiftUITests/CallingViews/MicrophoneChecker_Tests.swift
Resolves https://linear.app/stream/issue/IOS-730/[khealth]crash-on-microphonechecker
> [Fix]MicrophoneChecker receiveOn crash

- Package.swift
> Update SwiftProtobuf required version

- fastlane/Fastfile
Resolve: https://linear.app/stream/issue/IOS-761
Test: https://github.com/GetStream/apple-internal-testing-pipeline/actions/runs/14199661227/job/39783264302
> [CI] Remove concurrency module shadow on xcframeworks

- StreamVideoSwiftUITests/CallViewModel_Tests.swift
> [Fix]Linter error

- DemoApp/Sources/ViewModifiers/CallModifier/DemoCallModifier.swift
Part of https://linear.app/stream/project/livestream-sdk-improvements-55bc360bb997/overview.
Always show the livestream player when the call type is livestream.
> Updated demo app livestream presentation logic

- DocumentationTests/DocumentationTests/DocumentationTests.xcodeproj/project.pbxproj
- DocumentationTests/DocumentationTests/DocumentationTests/03-guides/13-livestreaming.swift
Part of https://linear.app/stream/project/livestream-sdk-improvements-55bc360bb997/overview.
Updated the documentation tests.
> Updated the documentation tests for livestreaming

- Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureVideoParticipantView.swift
Resolves https://linear.app/stream/issue/IOS-821/picture-in-picture-local-participant-not-mirrored
Provide a consistent video rendering experience for local participants.
> [Fix]Picture-in-Picture local participant not mirrored

- DemoApp/Sources/Components/AppEnvironment.swift
- DemoApp/Sources/Components/Authentication/AuthenticationProvider.swift
- DemoApp/Sources/Components/Deeplinks/DeeplinkAdapter.swift
- DemoApp/Sources/ViewModifiers/CallModifier/DemoCallModifier.swift
- DemoApp/Sources/Views/CallTopView/DemoCallTopView.swift
- DemoApp/Sources/Views/CallView/CallingView/DemoCallingViewModifier.swift
- DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
- DemoApp/Sources/Views/CallView/DemoVideoViewOverlay.swift
- StreamVideo.xcodeproj/project.pbxproj
Allow opening deeplinks from new domain.
> [Enhancement]Allow deeplinks from new domain

- Sources/StreamVideo/OpenApi/generated/Models/StatsOptions.swift
Part of https://linear.app/stream/issue/IOS-789/stats-v2-and-tracing.
> Updated StatsOptions model

- StreamVideoTests/Mock/MockResponseBuilder.swift
- StreamVideoTests/Utilities/Dummy/JoinCallResponse+Dummy.swift
- StreamVideoTests/WebRTC/v2/WebRTCAuthenticator_Tests.swift
Part of https://linear.app/stream/issue/IOS-789/stats-v2-and-tracing.
> Fixed broken tests

- Sources/StreamVideoSwiftUI/CallView/CallControls/Stateful/CallControlsView.swift
> [Fix]Avoid updating callControls while in-call

- README.md
Resolves https://linear.app/stream/issue/IOS-875/readme-updates.
> Added reference of the Chat SDK in the Readme

- .github/workflows/cron-checks.yml
- .github/workflows/smoke-checks.yml
Test: https://github.com/GetStream/stream-video-swift/actions/runs/15440886947
> [CI] Switch macos version to keep the support of Xcode 15.4

- .github/workflows/merge-main-to-develop.yml
- .github/workflows/release-publish.yml
- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
Resolve https://linear.app/stream/issue/IOS-920
Automate the release step of merging the main branch to develop
> [CI] Automate the release step of merging the main branch to develop

- CHANGELOG.md
- DemoApp/Sources/Components/Chat/DemoChatViewModel.swift
- DemoApp/Sources/Views/CallView/CallingView/SimpleCallingView.swift
- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/StreamVideo.swift
- Sources/StreamVideo/Utils/AudioSession/AudioRecorder/StreamCallAudioRecorder.swift
- Sources/StreamVideo/Utils/AudioSession/StreamAudioSession.swift
- Sources/StreamVideo/Utils/AudioSession/StreamRTCAudioSession.swift
- Sources/StreamVideo/Utils/CallCache/CallCache.swift
- Sources/StreamVideo/Utils/Proximity/Policies/SpeakerProximityPolicy.swift
- Sources/StreamVideo/Utils/Proximity/Policies/VideoProximityPolicy.swift
- Sources/StreamVideo/Utils/SerialActorQueue/OperationQueue+TaskOperations.swift
- Sources/StreamVideo/WebRTC/AudioFilter/Filters/NoiseCancellationFilter.swift
- Sources/StreamVideo/WebRTC/VideoCapturing/StreamVideoCaptureHandler.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalScreenShareMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalVideoMediaAdapter.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator.swift
- Sources/StreamVideo/WebRTC/v2/SFU/SFUEventAdapter.swift
- Sources/StreamVideo/WebRTC/v2/UpdateSubscriptions/WebRTCUpdateSubscriptionsAdapter.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
- Sources/StreamVideo/WebSockets/Client/URLSessionWebSocketEngine.swift
- Sources/StreamVideo/WebSockets/Events/WSEventsMiddleware.swift
- Sources/StreamVideoSwiftUI/CallViewModel.swift
- Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureStore.swift
- StreamVideoTests/Mock/MockStreamVideo.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
- StreamVideoTests/WebRTC/v2/WebRTCCoorindator_Tests.swift
Fix synchronisation issues between the OperationQueue and the executing tasks
> Fix synchronisation issues

- Sources/StreamVideo/Utils/AudioSession/Policies/OwnCapabilitiesAudioSessionPolicy.swift
- Sources/StreamVideo/WebRTC/v2/Extensions/AVFoundation/AVCaptureDevice+OutputFormat.swift
- Sources/StreamVideo/WebRTC/v2/Extensions/AVFoundation/AVCaptureDevice.Format+MediaSubType.swift
- Sources/StreamVideo/WebRTC/v2/PeerConnection/Protocols/CaptureDeviceProtocol.swift
- Sources/StreamVideo/WebRTC/v2/VideoCapturing/ActionHandlers/Camera/CameraCaptureHandler.swift
- StreamVideo.xcodeproj/project.pbxproj
- StreamVideoTests/Mock/MockCaptureDevice.swift
Ensure that we always capture on the best possible format for the capturing device.
> [Enhancement]Include the capturer preferredMediaSubtype in the requirements for the capturing format

- DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreControlsViewModifier.swift
- DemoApp/Sources/ViewModifiers/MoreControls/DemoMoreThermalStateButtonView.swift
- Sources/StreamVideo/Utils/AudioSession/AudioRecorder/AVAudioRecorderBuilder.swift
- Sources/StreamVideo/Utils/AudioSession/Extensions/AVAudioSession.CategoryOptions+Convenience.swift
- StreamVideo.xcodeproj/project.pbxproj
- StreamVideoTests/Utils/AudioSession/Extensions/AVAudioSessionCategoryOptions_Tests.swift
- StreamVideoTests/Utils/AudioSession/Policies/DefaultAudioSessionPolicyTests.swift
- StreamVideoTests/Utils/AudioSession/Policies/OwnCapabilitiesAudioSessionPolicyTests.swift
> Audio optimizations to the thermal state

- .swiftlint.yml
- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
> Fix issue with CallKit audio not working

- Sources/StreamVideo/Call.swift
- Sources/StreamVideo/CallKit/CallKitService.swift
- Sources/StreamVideo/Controllers/CallController.swift
- Sources/StreamVideo/Utils/AudioSession/StreamAudioSession.swift
- Sources/StreamVideo/Utils/AudioSession/StreamRTCAudioSession.swift
- Sources/StreamVideo/Utils/StreamAppStateAdapter/StreamAppStateAdapter.swift
- Sources/StreamVideo/WebRTC/PeerConnectionFactory.swift
- Sources/StreamVideo/WebRTC/v2/StateMachine/Stages/WebRTCCoordinator+Joined.swift
- Sources/StreamVideo/WebRTC/v2/Stats/Models/WebRTCTrace.swift
- Sources/StreamVideo/WebRTC/v2/Stats/Traces/WebRTCTracesAdapter.swift
- Sources/StreamVideo/WebRTC/v2/Stats/Traces/WebRTCTracing.swift
- Sources/StreamVideo/WebRTC/v2/Stats/WebRTCStatsAdapter.swift
- Sources/StreamVideo/WebRTC/v2/Stats/WebRTCStatsAdapting.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCCoordinator.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCStateAdapter.swift
- StreamVideoTests/Mock/MockAudioSession.swift
- StreamVideoTests/Mock/MockRTCPeerConnectionCoordinatorStack.swift
- StreamVideoTests/Mock/MockWebRTCStatsAdapter.swift
- StreamVideoTests/Mock/MockWebRTCTracesAdapter.swift
- StreamVideoTests/Utils/AudioSession/StreamAudioSession_Tests.swift
- StreamVideoTests/Utils/Proximity/Policies/SpeakerProximityPolicy_Tests.swift
- StreamVideoTests/Utils/StreamCallAudioRecorderTests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/AudioMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/LocalMediaAdapters/LocalAudioMediaAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/RTCPeerConnectionCoordinator_Tests.swift
- StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoinedStageTests.swift
- StreamVideoTests/WebRTC/v2/Stats/Models/WebRTCTrace_Tests.swift
- StreamVideoTests/WebRTC/v2/Stats/Traces/WebRTCTracesAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/Stats/WebRTCStatsAdapter_Tests.swift
Provide better tracing mainly around the AudioSession.
> [Enhancement]Improve tracing

- Sources/StreamVideo/Utils/SelectiveEncodable/Protobuf+SelectiveEncodable.swift
- Sources/StreamVideo/Utils/SelectiveEncodable/SelectiveEncodable.swift
Enrich the content of JoinRequest and UpdateSubscriptions traces.
> [Enhancement]Improve Stats for Join and UpdateSubscriptions

- StreamVideo-XCFramework.podspec
- StreamVideo.podspec
- StreamVideoSwiftUI-XCFramework.podspec
- StreamVideoSwiftUI.podspec
- StreamVideoUIKit-XCFramework.podspec
- StreamVideoUIKit.podspec
> Update license on Podspecs

- Sources/StreamVideoSwiftUI/CallView/VideoParticipantsView.swift
- Sources/StreamVideoSwiftUI/Utils/PictureInPicture/PictureInPictureParticipantModifier.swift
Part of https://linear.app/stream/issue/IOS-1072/ios-26-fixes.
iOS 26 PiP UI Fixes.
> Fixed speaking overlay in PiP on iOS 26

- Sources/StreamVideo/protobuf/sfu/models/models.pb.swift
> Codegen for audio bitrate type

- Sources/StreamVideo/protobuf/sfu/event/events.pb.swift
> Added unified session id to join request

- Sources/StreamVideo/Utils/IdleTimerAdapter/IdleTimerAdapter.swift
- StreamVideoTests/Utils/AudioSession/AudioRecorder/Namespace/Middleware/StreamCallAudioRecorder_ShouldRecordMiddlewareTests.swift
- StreamVideoTests/Utils/IdleTimerAdapter/IdleTimerAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/WebRTCAuthenticator_Tests.swift
> Fix cron tests

- Sources/StreamVideo/CallKit/CallKitService.swift
- Sources/StreamVideo/Utils/Extensions/Combine/Publisher+AsyncStream.swift
- Sources/StreamVideo/Utils/Logger/Logger.swift
- Sources/StreamVideo/Utils/PermissionsStore/Namespace/Components/CameraPermissionProvider.swift
- Sources/StreamVideo/Utils/PermissionsStore/Namespace/Components/MicrophonePermissionProvider.swift
- Sources/StreamVideo/Utils/PermissionsStore/Namespace/Components/PushNotificationsPermissionProvider.swift
- Sources/StreamVideo/Utils/Store/StoreNamespace.swift
- Sources/StreamVideo/WebRTC/Screensharing/BroadcastBufferReader.swift
- Sources/StreamVideo/WebRTC/v2/Extensions/AVFoundation/AVAudioRecorder+Sendable.swift
- Sources/StreamVideo/WebRTC/v2/VideoCapturing/ActionHandlers/Camera/CameraInterruptionsHandler.swift
- Sources/StreamVideo/WebRTC/v2/WebRTCConfiguration.swift
- StreamVideo.xcodeproj/project.pbxproj
- StreamVideo.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
- StreamVideo.xcodeproj/xcshareddata/xcschemes/DemoAppUIKit.xcscheme
- StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideo.xcscheme
- StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideoSwiftUI.xcscheme
- StreamVideo.xcodeproj/xcshareddata/xcschemes/StreamVideoUIKit.xcscheme
- StreamVideoTests/CallKit/CallKitServiceTests.swift
- StreamVideoTests/CallStateMachine/CallStateMachine/Stages/CallStateMachine_JoiningStageTests.swift
- StreamVideoTests/Mock/MockSFUStack.swift
- StreamVideoTests/StreamVideo_Tests.swift
- StreamVideoTests/Utils/Logger/LoggerConcurrency_Tests.swift
- StreamVideoTests/Utils/Store/Store_PerformanceTests.swift
- StreamVideoTests/WebRTC/v2/PeerConnection/MediaAdapters/Utilities/ApplicationLifecycleVideoMuteAdapter_Tests.swift
- StreamVideoTests/WebRTC/v2/StateMachine/Stages/WebRTCCoordinatorStateMachine_JoinedStageTests.swift
> [Fix]Tests and Warnings on Xcode 26
